### ISSUE TITLE
Subsequent calls to install.sh should work without an internet connection if a cached package is available

### ISSUE THREAD

**Issue by ioben** [chef/omnitruck#112]
Currently running `sudo bash install.sh -d /tmp/chef-install` caches the Chef client package, but it doesn't cache the downloaded metadata file (from https://www.chef.io/chef/metadata , line [522](https://github.com/chef/opscode-omnitruck/blob/584f5c7d115fe828c01eab8970079a7c812f50b5/views/install.sh.erb#L522)).  This means subsequent calls to the `install.sh` script fail if there is not an internet connection even though there is a cached version of the chef client package.

This seems like a bug, if I have a cached version of the package referenced it should work whether there is a network connection or not.  If the latest version is implicitly referenced than the latest version cached should be used if there is no network connection.

This can be achieved relatively easy by caching the output of the `do_download` call for the metadata file along with the cached package if a download directory is specified.

**Comment by jtimberman** [comment]
Hello,

I'm sorry that we never followed up on this issue. As it is quite old, I'm going to close it out. I'll label this as futuredev so we can possibly address this use case.

Cheers
Joshua
