### ISSUE TITLE
Omnitruck API v3

### ISSUE THREAD

**Issue by lamont-granquist** [chef/omnitruck#123]
Or maybe v2.99 since this will all be backwards compatible...
1.  Add a single new endpoint for everything which takes the 'project' as an argument.  Its real tedious to be adding new endpoints for new projects which is probably why we never do it.
2.  Projects should have major versions and optionally -current to pick up nightlies.  E.g. "chef-client-11", "chef-client-12", "chef-client-12-current", etc.  This solves the problem we had with "chef-server" and not being able to push 12.x servers into there because we were paranoid about major upgrading someone accidentally (chef-server-11, chef-server-12 and chef-server-12-current would at a minimum need to be supported, 13 getting added later, etc).
   
   a.  The existing chef-client endpoint should be maintained and be the unified set of chef-client-10+11+12 and if you pass -n it should add in the -current versions (Chef 13 would not be pushed to this endpoint).  Similarly the existing server endpoints should behave the same, the server endpoint has already been deprecated.   The code should be cleaned up so that the endpoints are one or two liners.
3.  Metadata should support #47 so we can just link directly to packagecloud repos and/or link to artifacts hosted by third parties (smartos?) outside of chef.
4.  Consider pulling and caching metadata directly out of packagecloud or having other metadata sources other than the s3 buckets (security implications though?), or supporting third party metadata buckets that we trust (e.g. smartos).  And this would just be to remove the hard coding, since hard coding is dumb, then we have the flexibility to do other things later if it makes sense, when it makes sense.

**Comment by jtimberman** [comment]
I'm closing this because the work hasn't been prioritized by anyone since the issue was opened. We may revisit design and functionality in Omnitruck at some point, and will consider this for future development. As such, the futuredev label has been added.
