### ISSUE TITLE
more refined full ist

### ISSUE THREAD

**Issue by jaymzh** [chef/omnitruck#128]
I'd love a version https://omnitruck.chef.io/current/full-chef-list that is querieable like normal omnitruck (os, release, etc.), and then returns a list of plain-text RPM URLs.

**Comment by MathildeBarr** [comment]
@schisamo We discussed this during a call with Phil, just checking in

**Comment by schisamo** [comment]
The best we have right now is filtering by version (`v`). I've chatted with @sersut about adding filtering by `p`, `pv` and `m` we just have been working on other higher priority things. We will accept a PR to add this filtering though.

The versions endpoint has this format: 
`http://omnitruck.chef.io/<CHANNEL>/<PROJECT>/versions?v=<VERSION>`. 

Here are some example queries: 
https://gist.github.com/schisamo/604f28e3e89d6626a232

**Comment by jaymzh** [comment]
You are missing the point here.

You guys want better testing - what I need is for you to make that easy.

What I want to run in cron on my machine:

```
wget <path_to_thing_that_gives_me_latest_build_of_rhel6>
# sanity check rpm
rpm -Uvh <rpm>
```

At the moment I have to do a quiery, grab JSON, parse JSON, build URLs... which means I'm not testing your latest builds which means I file P1 bugs AFTER you releaes which is MORE work for you guys. I'm trying to help you here, but you don't seem to want that. :(

**Comment by schisamo** [comment]
@jaymzh For that simple case can't you just do this:

```
 wget `curl -s "http://omnitruck.chef.io/current/chef/metadata?p=el&pv=6&m=x86_64" | awk '$1 == "url" { print $2 }'`
--2015-12-03 17:36:20--  http://opscode-omnibus-packages-current.s3.amazonaws.com/el/6/x86_64/chef-12.5.1%2B20151118085109-1.el6.x86_64.rpm
Resolving opscode-omnibus-packages-current.s3.amazonaws.com... 54.231.176.214
Connecting to opscode-omnibus-packages-current.s3.amazonaws.com|54.231.176.214|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 38262303 (36M) [application/x-www-form-urlencoded]
Saving to: 'chef-12.5.1+20151118085109-1.el6.x86_64.rpm'

chef-12.5.1+20151118085109-1.el6.x86_6   3%[=>                                                                            ]   1.11M   629KB/s
```

The `curl | awk` returns:

```
$ curl -s "http://omnitruck.chef.io/current/chef/metadata?p=el&pv=6&m=x86_64" | awk '$1 == "url" { print $2 }'
http://opscode-omnibus-packages-current.s3.amazonaws.com/el/6/x86_64/chef-12.5.1%2B20151118085109-1.el6.x86_64.rpm```

**Comment by jaymzh** [comment]
Aha! Your examples were all returning JSON which I didn't want to trust to awk/sed/cut.... but space-delimited stuff will work great, yes!

Will that be latest contbuild-built RPM?

**Comment by schisamo** [comment]
@jaymzh Yes it will be the latest build from the `current` channel. If you want the latest stable build just replace the `current` in the URL with `stable`.
