### ISSUE TITLE
Error on latest chef install, it instructed me to file this ticket

### ISSUE THREAD

**Issue by ibawolf** [chef/omnitruck#129]
Here's the output from an attempt to re-run the deb file install:

$ sudo dpkg -i /tmp/install.sh.2551/chef_12.4.3-1_amd64.deb
(Reading database ... 188781 files and directories currently installed.)
Preparing to unpack .../chef_12.4.3-1_amd64.deb ...
Unpacking chef (12.4.3-1) ...
dpkg-deb (subprocess): cannot copy archive member from '/tmp/install.sh.2551/chef_12.4.3-1_amd64.deb' to decompressor pipe: unexpected end of file or stream
dpkg-deb: error: subprocess paste returned error exit status 2
dpkg: error processing archive /tmp/install.sh.2551/chef_12.4.3-1_amd64.deb (--install):
 cannot copy extracted data for './opt/chef/embedded/lib/ruby/gems/2.1.0/cache/serverspec-2.24.0.gem' to '/opt/chef/embedded/lib/ruby/gems/2.1.0/cache/serverspec-2.24.0.gem.dpkg-new': unexpected end of file or stream
 Errors were encountered while processing:
  /tmp/install.sh.2551/chef_12.4.3-1_amd64.deb

**Comment by lamont-granquist** [comment]
if the downloaded package passed the checksums and was not corrupted then this would probably be an internal dpkg error, no idea how to fix it...
