### ISSUE TITLE
Omnibus installer on AIX fails with 12.4.3 client, worked OK with 12.4.1

### ISSUE THREAD

**Issue by tstrangio** [chef/omnitruck#132]
+-----------------------------------------------------------------------------+
                         Installing Software...
+-----------------------------------------------------------------------------+

installp: APPLYING software for:
        chef 12.4.3.1

Restoring files, please wait.
10004 files restored.
Thank you for installing Chef!
sysck: 3001-037 The name shain is not a known user for file
        /opt.
sysck: 3001-003 A value must be specified for owner for entry /opt.
sysck: 3001-017 Errors were detected validating the files
        for package chef.

installp:  The installation has FAILED for the "usr" part
        of the following filesets:
        chef 12.4.3.1

installp: Cleaning up software for:
        chef 12.4.3.1

Finished processing all filesets.  (Total time:  2 mins 7 secs).

+-----------------------------------------------------------------------------+
                                Summaries:
+-----------------------------------------------------------------------------+

Installation Summary
--------------------
Name                        Level           Part        Event       Result
-------------------------------------------------------------------------------
chef                        12.4.3.1        USR         APPLY       FAILED
chef                        12.4.3.1        USR         CLEANUP     SUCCESS
Installation failed

**Comment by jaym** [comment]
cc @schisamo @scotthain

**Comment by schisamo** [comment]
@tstrangio Can you please create a [new issue over on the Chef project](https://github.com/chef/chef/issues/new)? This isn't an Omnitruck issue.

**Comment by scotthain** [comment]
Closing in favor of https://github.com/chef/chef/issues/4031
