### ISSUE TITLE
Possibly incorrect chef server version for Ubuntu 14.04

### ISSUE THREAD

**Issue by jzohrab** [chef/omnitruck#166]
following docs at https://docs.chef.io/api_omnitruck.html. `https://www.chef.io/chef/metadata-server?p=ubuntu&pv=14.04&m=x86_64&v=latest` returns the following in Chrome browser: `url	https://opscode-omnibus-packages.s3.amazonaws.com/ubuntu/12.04/x86_64/chef-server_11.1.6-1_amd64.deb md5	d07cf230410b55bd8939ab29d65a3cc5 sha256 b0a27a0b04c30c102d65fa7e2f2f40f64e9cdde7ff07a453a91e1113b52929d8 version	11.1.6`

and curl:
```
$ curl -s 'https://www.chef.io/chef/metadata-server?p=ubuntu&pv=14.04&m=x86_64'
url	https://opscode-omnibus-packages.s3.amazonaws.com/ubuntu/12.04/x86_64/chef-server_11.1.6-1_amd64.deb
md5	d07cf230410b55bd8939ab29d65a3cc5
sha256	b0a27a0b04c30c102d65fa7e2f2f40f64e9cdde7ff07a453a91e1113b52929d8
```

https://packagecloud.io/chef/stable has various 12.x packages.  Is this intended?  Also the 14.04 pv is returning an ubuntu 12.04 url.

**Comment by echohack** [comment]
Hey @jzohrab ! Thank you for opening this issue.

The omnitruck API supported downloading the open source chef server 11 via the omnitruck api endpoint `/chef/metadata-server`. This is not supported for Chef Server 12.

For Chef Server 12 components, I would recommend using the chef-ingredient cookbook for downloading and install chef server primitives. It's awesome! https://github.com/chef-cookbooks/chef-ingredient

The omnitruck api is the primary way that users should download the chef-client (this is what the `knife bootstrap` process will use, for example). If you need to store chef-client binaries locally behind your firewall, I would recommend mirroring our brand new package repositories over at Bintray. You can read more about those here: https://www.chef.io/blog/2016/03/16/weve-moved-our-software-distribution-to-packages-chef-io/

If I answered your questions, please let me know and close the issue. Thank you!

**Comment by jzohrab** [comment]
Thanks @echohack.  I think this should stay open, as your notes above be added to README.md.  If you'd like I can take a shot at that and PR back.

**Comment by jzohrab** [comment]
Actually ref https://github.com/chef/omnitruck/pull/90, someone has brought this up already.

**Comment by lamont-granquist** [comment]
Yeah this is a dup of #90 and `p=ubuntu&pv=14.04` returning 12.04 packages is deliberately how it all works.
