### ISSUE TITLE
chef-solo: command not found

### ISSUE THREAD

**Issue by loihuynh0210** [chef/omnitruck#167]
$ ./install.sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 20022  100 20022    0     0  12466      0  0:00:01  0:00:01 --:--:-- 14109
Unable to determine platform version!
Version: 12.3.0

Please file a Bug Report at https://github.com/chef/omnitruck/issues/new
Alternatively, feel free to open a Support Ticket at https://www.chef.io/support                                                      /tickets
More Chef support resources can be found at https://www.chef.io/support

Please include as many details about the problem as possible i.e., how to reprod                                                      uce
the problem (if possible), type of the Operating System and its version, etc.,
and any other relevant details that might help us with troubleshooting.

./install.sh: line 21: chef-solo: command not found

**Comment by loihuynh0210** [comment]
Please, help me fixbug error.

**Comment by lamont-granquist** [comment]
"Unable to determine platform version!"

whatever O/S you're trying to install this on, we don't support with omnibus packages, you'll probably need to just `gem install chef`
