### ISSUE TITLE
chefclientinstall.sh fails

### ISSUE THREAD

**Issue by mcote55** [chef/omnitruck#172]
---------------------------------------------------------------------------
- Starting SetupClientOnLinux.sh at Wed Apr  6 17:59:11 UTC 2016
---------------------------------------------------------------------------
Arguments: teststash

Setup tmp area for installer files ...
   Tmp area: /tmp/chef_install.1159
Get the OS distribution and the version info ...
   This is Centos
   OS version: 7.0

--- Updating system hostname to 'teststash' ...
   Updated /etc/hosts.
   Updated /etc/sysconfig/network.

--- Test if Chef is loaded and that it the right version ...
   Chef not exist so download main installer files from bitbucket.aspect.com and run the installer ...
   Running curl chefclientinstall.sh
Downloading Chef 12.5.1 for el...
downloading https://www.opscode.com/chef/metadata?v=12.5.1&prerelease=false&nightlies=false&p=el&pv=7&m=x86_64
  to file /tmp/install.sh.1175/metadata.txt
trying curl...
sha1    9aa3e3d2e481b5c571991ee9cdf177eab8a6d640
sha256  7a937d8c0ab68a1f342aba4ad33417fc4ba8cb1a71f46e4a18b5e76c363e4075
url     https://packages.chef.io/stable/el/7/chef-12.5.1-1.el7.x86_64.rpm
version 12.5.1downloaded metadata file is corrupted or an uncaught error was encountered in downloading the file...
Version: 12.5.1

Please file a Bug Report at https://github.com/opscode/opscode-omnitruck/issues/new
Alternatively, feel free to open a Support Ticket at https://www.getchef.com/support/tickets
More Chef support resources can be found at https://www.getchef.com/support

Please include as many details about the problem as possible i.e., how to reproduce
the problem (if possible), type of the Operating System and its version, etc.,
and any other relevant details that might help us with troubleshooting.

-ERROR- Script chefclientinstall.sh failed with error code: 0

**Comment by litch** [comment]
I'm seeing the same thing in a fresh vagrant install.

**Comment by ntl** [comment]
Also experiencing this as well trying to install chef during a `vagrant up`.

**Comment by jjasghar** [comment]
I just gave this a shot on a tmp machine:

```
==> tmp: ubuntu 14.04 x86_64
==> tmp: Getting information for chef stable  for ubuntu...
==> tmp: downloading http://www.chef.io/stable/chef/metadata?v=&p=ubuntu&pv=14.04&m=x86_64
==> tmp:   to file /tmp/install.sh.2946/metadata.txt
==> tmp: trying wget...
==> tmp: sha1	d202d57512b6a2d795d0fb6df566ca906745c7d8
==> tmp: sha256	92b7f3eba0a62b20eced2eae03ec2a5e382da4b044c38c20d2902393683c77f7
==> tmp: url	https://packages.chef.io/stable/ubuntu/14.04/chef_12.8.1-1_amd64.deb
==> tmp: version	12.8.1
==> tmp: downloaded metadata file looks valid...
==> tmp: downloading https://packages.chef.io/stable/ubuntu/14.04/chef_12.8.1-1_amd64.deb
==> tmp:   to file /tmp/install.sh.2946/chef_12.8.1-1_amd64.deb
==> tmp: trying wget...
==> tmp: Comparing checksum with sha256sum...
==> tmp: WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING
==> tmp: You are installing an omnibus package without a version pin.  If you are installing
==> tmp: on production servers via an automated process this is DANGEROUS and you will
==> tmp: be upgraded without warning on new releases, even to new major releases.
==> tmp: Letting the version float is only appropriate in desktop, test, development or
==> tmp: CI/CD environments.
==> tmp: WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING
==> tmp: Installing chef
==> tmp: installing with dpkg...
```

**Comment by litch** [comment]
I should have mentioned, Nathan and I are using 12.5.1.

As is the OP.

**Comment by ntl** [comment]
It should be noted, when I tried 12.8.1 I got the same error.

**Comment by jjasghar** [comment]
Updated the install.sh and it looks like it fixed it. Please reopen if issue persists.

**Comment by mcote55** [comment]
I don't know how to reopen this, but it is still failing for me.  Do I need to do something on my end?
  Running curl chefclientinstall.sh
Downloading Chef 12.5.1 for el...
downloading https://www.opscode.com/chef/metadata?v=12.5.1&prerelease=false&nightlies=false&p=el&pv=7&m=x86_64
  to file /tmp/install.sh.12529/metadata.txt
trying curl...
sha1    9aa3e3d2e481b5c571991ee9cdf177eab8a6d640
sha256  7a937d8c0ab68a1f342aba4ad33417fc4ba8cb1a71f46e4a18b5e76c363e4075
url     https://packages.chef.io/stable/el/7/chef-12.5.1-1.el7.x86_64.rpm
version 12.5.1downloaded metadata file is corrupted or an uncaught error was encountered in downloading the file...
Version: 12.5.1

Please file a Bug Report at https://github.com/opscode/opscode-omnitruck/issues/new
Alternatively, feel free to open a Support Ticket at https://www.getchef.com/support/tickets
More Chef support resources can be found at https://www.getchef.com/support
