### ISSUE TITLE
the 'current' and 'stable' uri paths seem to be broken:

### ISSUE THREAD

**Issue by lamont-granquist** [chef/omnitruck#174]
12.9.41 is a 'current' artifact so this should work but it fails:

``` ruby
#curl https://omnitruck.chef.io/current/install.sh | sudo bash -s -- -v 12.9.41
```

while 12.9.38 from stable works:

``` ruby
# curl https://omnitruck.chef.io/current/install.sh | sudo bash -s -- -v 12.9.38
```

stable behaves exactly the same where this fails:

``` ruby
# curl https://omnitruck.chef.io/stable/install.sh | sudo bash -s -- -v 12.9.41
[...fails...]
# curl https://omnitruck.chef.io/stable/install.sh | sudo bash -s -- -v 12.9.38
[...fails....]
```

that means that to really get current you have to do:

``` ruby
# curl https://omnitruck.chef.io/current/install.sh | sudo bash -s -- -v 12.9.41 -c current
or 
# curl https://omnitruck.chef.io/current/install.sh | sudo bash -s -- -v 12.9.41 -n
```

for any users finding this issue wondering which workaround is correct, please use this for current:

``` ruby
# curl https://omnitruck.chef.io/current/install.sh | sudo bash -s -- -v 12.9.41 -c current
```

**Comment by jtimberman** [comment]
I'm closing this because the work hasn't been prioritized by anyone since the issue was opened, and we're many versions and releases past this  for Chef, now.
