### ISSUE TITLE
Chef-client 12.4.1 not found for solaris 2

### ISSUE THREAD

**Issue by MarkGibbons** [chef/omnitruck#175]
Hello,
I get this output running test kitchen with require_chef_omnibus: 12.4.1  I would like to be able to test this specific version.  The messages indicate that no 12.14.1 version exists to be downloaded.  My test environment versions are:
Chef Development Kit Version: 0.10.0
chef-client version: 12.5.1
berks version: 4.0.1
kitchen version: 1.4.2

thanks,
  Mark

-----> Converging <default-qas-sol10>...
       Preparing files for transfer
       Preparing dna.json
       Resolving cookbook dependencies with Berkshelf 4.0.1...
       Removing non-cookbook files before transfer
       Preparing validation.pem
       Preparing client.rb
-----> Installing Chef Omnibus (12.4.1)
       Downloading http://www.chef.io/chef/install.sh to file /tmp/install.sh
       Trying wget...
       Download complete.
       grep: illegal option -- q
       Usage: grep -hblcnsviw pattern file . . .
       solaris2 5.10 i386
       Getting information for chef stable 12.4.1 for solaris2...
       downloading http://www.getchef.com/stable/chef/metadata?v=12.4.1&p=solaris2&pv=5.10&m=i386
         to file /tmp/install.sh.823/metadata.txt
       trying wget...
       ERROR 404
       Omnitruck artifact does not exist for version 12.4.1 on platform solaris2

       Either this means:
          - We do not support solaris2
          - We do not have an artifact for 12.4.1

       This is often the latter case due to running a prerelease or RC version of chef
       or a gem version which was only pushed to rubygems and not omnitruck.

       You may be able to set your knife[:bootstrap_version] to the most recent stable
       release of Chef to fix this problem (or the most recent stable major version number).

       In order to test the version parameter, adventurous users may take the Metadata URL
       below and modify the '&v=<number>' parameter until you successfully get a URL that
       does not 404 (e.g. via curl or wget).  You should be able to use '&v=11' or '&v=12'
       succesfully.

       If you cannot fix this problem by setting the bootstrap_version, it probably means
       that solaris2 is not supported.

       Metadata URL: http://www.getchef.com/stable/chef/metadata?v=12.4.1&p=solaris2&pv=5.10&m=i386
>>>>>> Converge failed on instance <default-qas-sol10>.
>>>>>> Please see .kitchen/logs/default-qas-sol10.log for more details
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: SSH exited (1) for command: [sh -c '
http_proxy="http://webproxysea.nordstrom.net:8181"; export http_proxy
HTTP_PROXY="http://webproxysea.nordstrom.net:8181"; export HTTP_PROXY
https_proxy="http://webproxysea.nordstrom.net:8181"; export https_proxy
HTTPS_PROXY="http://webproxysea.nordstrom.net:8181"; export HTTPS_PROXY
chef_omnibus_root="/opt/chef"
chef_omnibus_url="https://www.chef.io/chef/install.sh"
install_flags="-v 12.4.1"
pretty_version="12.4.1"
sudo_sh="sudo -E sh"
version="12.4.1"

**Comment by sersut** [comment]
Thanks for bringing this to our attention @MarkGibbons. This should be all fixed now. Let us know if it is not.
