### ISSUE TITLE
Solaris2 download of chef client 12.9.38 fails.

### ISSUE THREAD

**Issue by MarkGibbons** [chef/omnitruck#176]
I'm trying to use test kitchen to test a solaris 10 instance I specify require_chef_omnibus: latest.   I get this output. Using wget on the my local image I get this message

ERROR: cannot verify packages.chef.io's certificate, issued by `/C=US/O=GeoTrust Inc./CN=GeoTrust SSL CA - G3':
  Unable to locally verify the issuer's authority.
ERROR: certificate common name `*.bintray.com' doesn't match requested host name `packages.chef.io'.
To connect to packages.chef.io insecurely, use `--no-check-certificate'.

 trying to retrieve using 

**https**://packages.chef.io/stable/solaris2/5.10/chef-12.9.38-1.i386.solaris 
or
**http:**//packages.chef.io/stable/solaris2/5.10/chef-12.9.38-1.i386.solaris

It looks like retrieving from http is forwarded to the https url, which won't work for solaris.  I've reported similar issues in the past.  Something in the build process is not making an exception for Solaris.

Thanks,
   Mark

ERROR: cannot verify packages.chef.io's certificate, issued by `/C=US/O=GeoTrust Inc./CN=GeoTrust SSL CA - G3':
  Unable to locally verify the issuer's authority.
ERROR: certificate common name `*.bintray.com' doesn't match requested host name `packages.chef.io'.
To connect to packages.chef.io insecurely, use `--no-check-certificate'.

-----> Converging <default-qas-sol10>...
       Preparing files for transfer
       Preparing dna.json
       Resolving cookbook dependencies with Berkshelf 4.0.1...
       Removing non-cookbook files before transfer
       Preparing validation.pem
       Preparing client.rb
-----> Installing Chef Omnibus (always install latest version)
       Downloading http://www.chef.io/chef/install.sh to file /tmp/install.sh
       Trying wget...
       Download complete.
       grep: illegal option -- q
       Usage: grep -hblcnsviw pattern file . . .
       solaris2 5.10 i386
       Getting information for chef stable  for solaris2...
       downloading http://www.chef.io/stable/chef/metadata?v=&p=solaris2&pv=5.10&m=i386
         to file /tmp/install.sh.957/metadata.txt
       trying wget...
       sha1    b27c39e3fc1624c7b62001589fd1fa7ad56dd1f7
       sha256  0718754227fbdbf4e582384eda93a4ce869581764fa526c64dff4a576e4966ad
       url     https://packages.chef.io/stable/solaris2/5.10/chef-12.9.38-1.i386.solaris

       downloaded metadata file looks valid...
       downloading https://packages.chef.io/stable/solaris2/5.10/chef-12.9.38-1.i386.solaris
         to file /tmp/install.sh.957/chef-12.9.38-1.i386.solaris
       trying wget...
       trying perl...
       Unable to retrieve a valid package!
       Version:

       Please file a Bug Report at https://github.com/chef/omnitruck/issues/new
       Alternatively, feel free to open a Support Ticket at https://www.chef.io/support/tickets
       More Chef support resources can be found at https://www.chef.io/support

       Please include as many details about the problem as possible i.e., how to reproduce
       the problem (if possible), type of the Operating System and its version, etc.,
       and any other relevant details that might help us with troubleshooting.

       Metadata URL: http://www.chef.io/stable/chef/metadata?v=&p=solaris2&pv=5.10&m=i386
       Download URL: https://packages.chef.io/stable/solaris2/5.10/chef-12.9.38-1.i386.solaris

       DEBUG OUTPUT FOLLOWS:

       STDERR from wget:

       --2016-04-22 15:30:11--  http://packages.chef.io/stable/solaris2/5.10/chef-12.9.38-1.i386.solaris
       Resolving webproxysea.nordstrom.net... 10.12.146.20
       connected.
       Proxy request sent, awaiting response... 302 Found
       Location: https://packages.chef.io/stable/solaris2/5.10/chef-12.9.38-1.i386.solaris [following]
       s
       Connecting to webproxysea.nordstrom.net|10.12.146.20|:8181... connected.
       ERROR: cannot verify packages.chef.io's certificate, issued by `/C=US/O=GeoTrust Inc./CN=GeoTrust SSL CA - G3':
         Unable to locally verify the issuer's authority.
       e common name `*.bintray.com' doesn't match requested host name `packages.chef.io'.
       To connect to packages.chef.io insecurely, use `--no-check-certificate'.

       STDERR from perl:

       solaris-64int /usr/perl5/5.8.4/lib /usr/perl5/site_perl/5.8.4/i86pc-solaris-64int /usr/perl5/site_perl/5.8.4 /usr/perl5/site_perl /usr/perl5/vendor_perl/5.8.4/i86pc-solaris-64int /usr/perl5/vendor_perl/5.8.4 /usr/perl5/vendor_perl .) at -e line 1.
       ailed--compilation aborted at -e line 1.

**Comment by sersut** [comment]
This will be fixed whenw e re-deploy omnitruck, very soon 😄

**Comment by sersut** [comment]
Now all should be good 😄
