### ISSUE TITLE
chef-client on solaris - asked for 12.4.1 got latest

### ISSUE THREAD

**Issue by MarkGibbons** [chef/omnitruck#178]
Thanks for working on the other solaris install issues.

New issue.
My .kitchen.yml file has "require_chef_omnibus 12.4.1"

I got the following trying to install 12.9.38, plus warnings saying I was installing without a version pin:

-----> Installing Chef Omnibus (install only if missing)
       Downloading https://www.chef.io/chef/install.sh to file /tmp/install.sh
       Trying wget...
       Download complete.
       solaris2 5.11 i386
       Getting information for chef stable  for solaris2...
       downloading https://omnitruck-direct.chef.io/stable/chef/metadata?v=&p=solaris2&pv=5.11&m=i386
         to file /tmp/install.sh.2056/metadata.txt
       trying wget...
       sha1    b27c39e3fc1624c7b62001589fd1fa7ad56dd1f7
       sha256  0718754227fbdbf4e582384eda93a4ce869581764fa526c64dff4a576e4966ad
       url     https://packages.chef.io/stable/solaris2/5.11/chef-12.9.38-1.i386.solaris
       version 12.9.38
       downloaded metadata file looks valid...
       downloading https://packages.chef.io/stable/solaris2/5.11/chef-12.9.38-1.i386.solaris
         to file /tmp/install.sh.2056/chef-12.9.38-1.i386.solaris
       trying wget...
       Comparing checksum with sha256sum...

       WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING

       You are installing an omnibus package without a version pin.  If you are installing
       on production servers via an automated process this is DANGEROUS and you will
       be upgraded without warning on new releases, even to new major releases.
       Letting the version float is only appropriate in desktop, test, development or
       CI/CD environments.

       WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING

**Comment by sersut** [comment]
What's the version of test-kitchen? 

With https://github.com/test-kitchen/test-kitchen/pull/976 we have moved to a different set of options (`product_name`, `product_version` and `channel`) and something around it might be giving you that warning. 

It might be faster to ask about that in https://github.com/test-kitchen/test-kitchen.

**Comment by MarkGibbons** [comment]
Chef Development Kit Version: 0.10.0
chef-client version: 12.5.1
berks version: 4.0.1
kitchen version: 1.4.2

**Comment by sersut** [comment]
@chef/test-kitchen-collaborators any ideas about this?

**Comment by MarkGibbons** [comment]
Sorry, I had a typo in my .kitchen.yml file that caused this one.
