### ISSUE TITLE
installing_chef_client_bug

### ISSUE THREAD

**Issue by teja624** [chef/omnitruck#186]
192.168.15.76   File "<string>", line 1, in <module>
192.168.15.76   File "/usr/lib64/python2.7/urllib2.py", line 154, in urlopen
192.168.15.76     return opener.open(url, data, timeout)
192.168.15.76   File "/usr/lib64/python2.7/urllib2.py", line 431, in open
192.168.15.76     response = self._open(req, data)
192.168.15.76   File "/usr/lib64/python2.7/urllib2.py", line 449, in _open
192.168.15.76     '_open', req)
192.168.15.76   File "/usr/lib64/python2.7/urllib2.py", line 409, in _call_chain
192.168.15.76     result = func(*args)
192.168.15.76   File "/usr/lib64/python2.7/urllib2.py", line 1258, in https_open
192.168.15.76     context=self._context, check_hostname=self._check_hostname)
192.168.15.76   File "/usr/lib64/python2.7/urllib2.py", line 1214, in do_open
192.168.15.76     raise URLError(err)
192.168.15.76 urllib2.URLError: <urlopen error [Errno 104] Connection reset by peer>\n
192.168.15.76 Starting the first Chef Client run...
192.168.15.76 sh: line 257: chef-client: command not found
You have new mail in /var/spool/mail/root

**Comment by jtimberman** [comment]
Hello,

I'm sorry that we never followed up on this issue! As it is quite old and there have been many changes to the products and operating systems involved, I'm going to close this issue, as reproducing it would be difficult, if not impossible.

Cheers
Joshua
