### ISSUE TITLE
Chef Bootstrapping Node Error

### ISSUE THREAD

**Issue by yerollashyam** [chef/omnitruck#188]
Hello, 
 I am able to install chef on workstation (curl -L https://www.opscode.com/chef/install.sh | sudo bash)
this was success and when I try to bootstrap a node (knife bootstrap <address> -x user -P password -N <n>) it show following error...
=======================================================================
[root@yerollashyam4 cookbooks]# knife bootstrap yerollashyam5b.mylabserver.com -x user -P password -N Node
Creating new client for Node
Creating new node for Node
Connecting to yerollashyam5b.mylabserver.com
user@yerollashyam5b.mylabserver.com's password: 
yerollashyam5b.mylabserver.com -----> Installing Chef Omnibus (-v 12)
yerollashyam5b.mylabserver.com downloading https://omnitruck-direct.chef.io/chef/install.sh
yerollashyam5b.mylabserver.com   to file /tmp/install.sh.6067/install.sh
yerollashyam5b.mylabserver.com trying wget...
yerollashyam5b.mylabserver.com el 6 x86_64
yerollashyam5b.mylabserver.com Getting information for chef stable 12 for el...
yerollashyam5b.mylabserver.com downloading https://omnitruck-direct.chef.io/stable/chef/metadata?v=12&p=el&pv=6&m=x86_64
yerollashyam5b.mylabserver.com   to file /tmp/install.sh.6078/metadata.txt
yerollashyam5b.mylabserver.com trying wget...
yerollashyam5b.mylabserver.com sha1     22c01541188bf6b79d65f3f897a34d30581edf55
yerollashyam5b.mylabserver.com sha256   909a4f3e1738ceefc8ee8e16da2b4bd35f63d51a7854aea744c3caeb84d1ef29
yerollashyam5b.mylabserver.com url      https://packages.chef.io/stable/el/6/chef-12.12.13-1.el6.x86_64.rpm
yerollashyam5b.mylabserver.com version  12.12.13
yerollashyam5b.mylabserver.com downloaded metadata file looks valid...
yerollashyam5b.mylabserver.com downloading https://packages.chef.io/stable/el/6/chef-12.12.13-1.el6.x86_64.rpm
yerollashyam5b.mylabserver.com   to file /tmp/install.sh.6078/chef-12.12.13-1.el6.x86_64.rpm
yerollashyam5b.mylabserver.com trying wget...
yerollashyam5b.mylabserver.com Comparing checksum with sha256sum...
yerollashyam5b.mylabserver.com Installing chef 12
yerollashyam5b.mylabserver.com installing with rpm...
yerollashyam5b.mylabserver.com warning: /tmp/install.sh.6078/chef-12.12.13-1.el6.x86_64.rpm: Header V4 DSA/SHA1 Signature, key ID 83ef826a: NOKEY
yerollashyam5b.mylabserver.com error: can't create transaction lock on /var/lib/rpm/.rpm.lock (Permission denied)
yerollashyam5b.mylabserver.com Installation failed
yerollashyam5b.mylabserver.com Version: 12
yerollashyam5b.mylabserver.com 
yerollashyam5b.mylabserver.com Please file a Bug Report at https://github.com/chef/omnitruck/issues/new
yerollashyam5b.mylabserver.com Alternatively, feel free to open a Support Ticket at https://www.chef.io/support/tickets
yerollashyam5b.mylabserver.com More Chef support resources can be found at https://www.chef.io/support
yerollashyam5b.mylabserver.com 
yerollashyam5b.mylabserver.com Please include as many details about the problem as possible i.e., how to reproduce
yerollashyam5b.mylabserver.com the problem (if possible), type of the Operating System and its version, etc.,
yerollashyam5b.mylabserver.com and any other relevant details that might help us with troubleshooting.
yerollashyam5b.mylabserver.com 
yerollashyam5b.mylabserver.com mkdir: cannot create directory `/etc/chef': Permission denied
yerollashyam5b.mylabserver.com sh: line 178: /etc/chef/client.pem: No such file or directory
yerollashyam5b.mylabserver.com chmod: cannot access `/etc/chef/client.pem': No such file or directory
yerollashyam5b.mylabserver.com sh: line 214: /etc/chef/client.rb: No such file or directory
yerollashyam5b.mylabserver.com sh: line 222: /etc/chef/first-boot.json: No such file or directory
yerollashyam5b.mylabserver.com Starting the first Chef Client run...
yerollashyam5b.mylabserver.com sh: line 229: chef-client: command not found
=============================================================================
Before, I have started the bootstrap I have enabled the root permit login in node server(/etc/ssh/sshd_config & restarted the service sshd).
Requesting  all for solution.

Thanks-

**Comment by yzl** [comment]
@yerollashyam From the following lines in your error message:

```
yerollashyam5b.mylabserver.com error: can't create transaction lock on /var/lib/rpm/.rpm.lock (Permission denied)
yerollashyam5b.mylabserver.com Installation failed
```

there is a permissions issue.   What happens if you add the `--sudo` flag to your bootstrap command, e.g.
`knife bootstrap yerollashyam5b.mylabserver.com -x user -P password -N Node --sudo`?

reference:  https://docs.chef.io/install_bootstrap.html

**Comment by yerollashyam** [comment]
Hello @yzl , I tired using the above command 
=========================================
[root@yerollashyam4 chef-repo]#  knife bootstrap yerollashyam5b.mylabserver.com -x user -P password -N Node --sudo 
Creating new client for Node
Creating new node for Node
Connecting to yerollashyam5b.mylabserver.com
user@yerollashyam5b.mylabserver.com's password: 
yerollashyam5b.mylabserver.com knife sudo password: 
Enter your password: 
yerollashyam5b.mylabserver.com 
yerollashyam5b.mylabserver.com user is not in the sudoers file.  This incident will be reported.
[root@yerollashyam4 chef-repo]# 
=============================================

**Comment by yzl** [comment]
@yerollashyam According to the [docs for knife bootstrap](https://docs.chef.io/knife_bootstrap.html), you can specify a password with a combination of `--ssh-password` and `--use-sudo-password`.  There are further examples/discussion in [this stackoverflow thread](http://stackoverflow.com/questions/18435513/knife-bootstrap-command-without-prompting-password).

**Comment by yerollashyam** [comment]
Hey @yzl ,

Nothing worked out. Shows same error :( :(

**Comment by yzl** [comment]
@yerollashyam I'm sorry that didn't work!  At this point, I'm going to suggest that you share your question in [chef's discourse forum](https://discourse.chef.io/) or in [chef's IRC channel](http://irc.lc/freenode/chef), where there are more people available to dig into what's going on.

**Comment by scotthain** [comment]
@yerollashyam the error you're describing is a generic RPM error that can be caused by a few things. Typically the main reason is the user does not have sudo privileges. Another reason can be the lock file getting into a bad state.

From the error you have shown, it looks like your user is not the in sudoers file. As @yzl mentioned - I would recommend sharing your question on chef's discourse forum, as there are many folks there who may have run into similar issues.

**Comment by yerollashyam** [comment]
Hey thanks @yzl  @scotthain for the suggestion I have posted in the chef's discourse forum.
And I have have more question Will I be able to link chef server to TFS(Version Control). I know this can be done with GitHub but also don't know if it is possible with TFS even?

**Comment by yerollashyam** [comment]
Fixed the Issue by adding the user in sudoer's list and executing it.

**Comment by scotthain** [comment]
Glad to hear it!
