### ISSUE TITLE
chef downloads x64 package on 32-bit VM

### ISSUE THREAD

**Issue by pjjohnstone** [chef/omnitruck#190]
Using windows 7 Enterprise, the VM identifies itself as a 32-bit OS, but chef fetches and attempts to install the 64bit client MSI, failing with error code 1633.

[win732bootstrap.txt](https://github.com/chef/omnitruck/files/376074/win732bootstrap.txt)

**Comment by jtimberman** [comment]
Hello,

I'm sorry that we never followed up on this issue! As it is quite old and there have been many changes to the products and operating systems involved, I'm going to close this issue.

Cheers
Joshua
