### ISSUE TITLE
Erro in AIX instance bootstrap using non root user

### ISSUE THREAD

**Issue by yogeshrathore1992** [chef/omnitruck#194]
Comparing checksum with shasum...
X.X.X.X  Installing chef 12
X.X.X.X  installing with installp...
X.X.X.X  /tmp/install.sh.2621886/install.sh[18]: installp: 0403-006 Execute permission denied.
X.X.X.X  Installation failed
X.X.X.X  Version: 12

**Comment by jtimberman** [comment]
You need to use `sudo` or log in as root. The omnibus package of Chef installs in `/opt`.
