### ISSUE TITLE
Access denied Chef 12 

### ISSUE THREAD

**Issue by AshishSanju** [chef/omnitruck#195]
I am trying to install the client on to my UBUNTU server, I have all the privileges as the root user..!!
192.168.x.x   to file /tmp/install.sh.3853/chef_12.13.37-1_amd64.deb
192.168.x.x trying wget...
192.168.x.x Comparing checksum with sha256sum...
192.168.x.x Installing chef 12
192.168.x.x installing with dpkg...
192.168.x.x dpkg: error: requested operation requires superuser privilege
192.168.x.x Installation failed
192.168.x.x Version: 12
192.168.x.x
192.168.x.x Please file a Bug Report at https://github.com/chef/omnitruck/issues                                                                                        /new
192.168.x.x Alternatively, feel free to open a Support Ticket at https://www.che                                                                                        f.io/support/tickets
192.168.x.x More Chef support resources can be found at https://www.chef.io/supp                                                                                        ort
192.168.x.x
192.168.x.x Please include as many details about the problem as possible i.e., h                                                                                        ow to reproduce
192.168.x.x the problem (if possible), type of the Operating System and its vers                                                                                        ion, etc.,
192.168.x.x and any other relevant details that might help us with troubleshooti                                                                                        ng.
192.168.x.x
192.168.x.x mkdir: cannot create directory ‘/etc/chef’: Permission denied
192.168.x.x sh: 179: cannot create /etc/chef/client.pem: Directory nonexistent
192.168.x.x chmod: cannot access '/etc/chef/client.pem': No such file or directo                                                                                        ry
192.168.x.x sh: 215: cannot create /etc/chef/client.rb: Directory nonexistent
192.168.x.x sh: 223: cannot create /etc/chef/first-boot.json: Directory nonexist                                                                                        ent
192.168.x.x Starting the first Chef Client run...
192.168.x.x sh: 230: chef-client: not found

**Comment by thommay** [comment]
This isn't a bug - you're clearly not running with those privileges. Either use sudo (preferred) or run as root.
