### ISSUE TITLE
Alpine linux support

### ISSUE THREAD

**Issue by juju4** [chef/omnitruck#199]
Hello,

Any plan for install.sh to support Alpine Linux ?

Thanks

**Comment by IronCore864** [comment]
It's been 1.5 years. Why no support to alpine?

I think it makes great sense for test-kitchen/chef/serverspec/ansible with docker to do infrastructure code test or even test-driven infrastructure code develeopment. alpine makes it much smaller and faster to use.

Is there a specific reason why not supporting alpine? I'm not familiar with different distributions of linux, maybe there is some block issue?

**Comment by thommay** [comment]
We don't intend to support Alpine. We already provide docker images that contain chef and chefdk for use with test kitchen (see someara/kitchen-dokken) or to use the chefdk tooling in docker.
Providing support for Alpine means much more than just installing; we need to test, verify and add support for the way alpine works to chef, and there just isn't sufficient demand for that - and we think that Habitat is a better way to build and configure containers.

**Comment by zedtux** [comment]
In my use case, I'm running with GitLab CI, meaning Docker In Docker.

Official Docker's images are based on Alpine, so I have to use the `docker` Docker image, and have the `kitchen` command available.

@thommay of course it means more than installing Alpine, but Alpine is really popular in the Docker community, not supporting it sounds like closing the door to a lot of users IMHO.
