### ISSUE TITLE
Publish checksums of install scripts on omnitruck

### ISSUE THREAD

**Issue by adhodgson1** [chef/omnitruck#201]
It would be useful if checksums for the install.sh and install.ps1 scripts could be published somewhere on Omnitruck so we can verify the installer scripts before downloading.  We have to verify all checksums before downloading files from remote locations, and currently we manually publish the checksum of the install scripts and as these change offen they have to be updated.

**Comment by jtimberman** [comment]
That is an interesting idea. A challenge with it is that the install scripts are generated based on the various parameters through the [mixlib-install](https://github.com/chef/mixlib-install/) library.

**Comment by jtimberman** [comment]
I'm sorry that we never followed up on this issue! 

At this point, the install scripts themselves are generated by a library in Omnitruck, and getting a checksum of that would be nearly impossible given it's built based on the operating system and versions involved.
