### ISSUE TITLE
Unable to retrieve a valid package!

### ISSUE THREAD

**Issue by tejakakaraparthi** [chef/omnitruck#210]
[vagrant@rhel-cdk ~]$ curl -L https://omnitruck.chef.io/install.sh | sudo bash -s -- -P chefdk -c stable -v 0.18.30
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 20500  100 20500    0     0  40703      0 --:--:-- --:--:-- --:--:-- 40674
el 7 x86_64
Getting information for chefdk stable 0.18.30 for el...
downloading https://omnitruck.chef.io/stable/chefdk/metadata?v=0.18.30&p=el&pv=7&m=x86_64
  to file /tmp/install.sh.16614/metadata.txt
trying curl...
trying perl...
trying python...
Unable to retrieve a valid package!
Version: 0.18.30

Please file a Bug Report at https://github.com/chef/omnitruck/issues/new
Alternatively, feel free to open a Support Ticket at https://www.chef.io/support/tickets
More Chef support resources can be found at https://www.chef.io/support

Please include as many details about the problem as possible i.e., how to reproduce
the problem (if possible), type of the Operating System and its version, etc.,
and any other relevant details that might help us with troubleshooting.

Metadata URL: https://omnitruck.chef.io/stable/chefdk/metadata?v=0.18.30&p=el&pv=7&m=x86_64
\nDEBUG OUTPUT FOLLOWS:\n\nSTDERR from curl:\n\n\n\nSTDERR from perl:\n\nCan't locate LWP/Simple.pm in @INC (@INC contains: /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .) at -e line 1.
BEGIN failed--compilation aborted at -e line 1.\n\nSTDERR from python:\n\nTraceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib64/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib64/python2.7/urllib2.py", line 431, in open
    response = self._open(req, data)
  File "/usr/lib64/python2.7/urllib2.py", line 449, in _open
    '_open', req)
  File "/usr/lib64/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 1258, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/usr/lib64/python2.7/urllib2.py", line 1214, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [Errno 111] Connection refused>\n

**Comment by tas50** [comment]
If you're falling back to python it's because we couldn't find a simpler tool like curl or wget. If you install curl or wget on the system first this will go away. Sorry it took so long to get a response.
