### ISSUE TITLE
Onminbus chef installation started failing

### ISSUE THREAD

**Issue by debashis1982** [chef/omnitruck#212]
Installation log:
####################
Updating / installing...
chef-12.19.36-1.el7                   #el 7 x86_64
Getting information for chef stable  for el...
downloading https://omnitruck.chef.io/stable/chef/metadata?v=&p=el&pv=7&m=x86_64
  to file /tmp/install.sh.9381/metadata.txt
trying curl...
sha1    5e36301f5e751f2a79a8b513831b5bc0b478bbed
sha256  124d34d3a26ce25305899bc93df58aaf4979c5c065adcf1e6487734afb6edf6c
url     https://packages.chef.io/files/stable/chef/12.19.36/el/7/chef-12.19.36-1.el7.x86_64.rpm
version 12.19.36
downloaded metadata file looks valid...
downloading https://packages.chef.io/files/stable/chef/12.19.36/el/7/chef-12.19.36-1.el7.x86_64.rpm
  to file /tmp/install.sh.9381/chef-12.19.36-1.el7.x86_64.rpm
trying curl...
#####################Comparing checksum with sha256sum...

WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING

You are installing an omnibus package without a version pin.  If you are installing
on production servers via an automated process this is DANGEROUS and you will
be upgraded without warning on new releases, even to new major releases.
Letting the version float is only appropriate in desktop, test, development or
CI/CD environments.

WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING

Installing chef
installing with rpm...
##################
Thank you for installing Chef!
Cleaning up / removing...
chef-12.6.0-1.el7                     ########################################
Preparing...                          ########################################
Updating / installing...
chef-12.19.36-1.el7                   ########################################
Thank you for installing Chef!
Installation failed
Version:

Please file a Bug Report at https://github.com/chef/omnitruck/issues/new
Alternatively, feel free to open a Support Ticket at https://www.chef.io/support/tickets
More Chef support resources can be found at https://www.chef.io/support

Please include as many details about the problem as possible i.e., how to reproduce
the problem (if possible), type of the Operating System and its version, etc.,
and any other relevant details that might help us with troubleshooting.

**Comment by dfduarte** [comment]
Hello

Just to report, I'm facing exactly the same issue here, but using the Docker and Vagrant plugins.

```
       Removing non-cookbook files before transfer
       Preparing validation.pem
       Preparing client.rb
-----> Installing Chef Omnibus (13)
       Downloading https://omnitruck.chef.io/install.sh to file /tmp/install.sh
       Trying wget...
       Trying curl...
	       Trying python...
       Unable to download https://omnitruck.chef.io/install.sh to /tmp/install.sh, aborting
       \nDEBUG OUTPUT FOLLOWS:\n\nSTDERR from wget:\n\n--2017-04-26 14:10:39--  https://omnitruck.chef.io/install.sh
       Resolving proxy-dev.frg.tech (proxy-dev.frg.tech)... 92.242.140.6
       Connecting to proxy-dev.frg.tech (proxy-dev.frg.tech)|92.242.140.6|:3128... failed: Connection timed out.
       Retrying.
       
       --2017-04-26 14:12:47--  (try: 2)  https://omnitruck.chef.io/install.sh
       Connecting to proxy-dev.frg.tech (proxy-dev.frg.tech)|92.242.140.6|:3128... failed: Connection timed out.
       Retrying.
       
       --2017-04-26 14:14:57--  (try: 3)  https://omnitruck.chef.io/install.sh
       Connecting to proxy-dev.frg.tech (proxy-dev.frg.tech)|92.242.140.6|:3128... failed: Connection refused.\n\nSTDERR from curl:\n\n\n\nSTDERR from python:\n\nTraceback (most recent call last):
         File "<string>", line 1, in <module>
         File "/usr/lib64/python2.7/urllib2.py", line 154, in urlopen
           return opener.open(url, data, timeout)
         File "/usr/lib64/python2.7/urllib2.py", line 431, in open
           response = self._open(req, data)
         File "/usr/lib64/python2.7/urllib2.py", line 449, in _open
           '_open', req)
         File "/usr/lib64/python2.7/urllib2.py", line 409, in _call_chain
           result = func(*args)
         File "/usr/lib64/python2.7/urllib2.py", line 1258, in https_open
           context=self._context, check_hostname=self._check_hostname)
         File "/usr/lib64/python2.7/urllib2.py", line 1214, in do_open
           raise URLError(err)
       urllib2.URLError: <urlopen error [Errno 111] Connection refused>\n
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: 1 actions failed.
>>>>>>     Converge failed on instance <default-centos-72>.  Please see .kitchen/logs/default-centos-72.log for more details
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration


```

**Comment by dfduarte** [comment]
Edit:

Sorry guys, just found the problem. A misconfigured proxy has acting in the provisioner: config.

**Comment by debashis1982** [comment]
Closing as it is working now
