### ISSUE TITLE
install script fails on Windows 10 for inspec, chef and chef-dk

### ISSUE THREAD

**Issue by chris-rock** [chef/omnitruck#213]
The installation of the InSpec package via 
```
. { iwr -useb https://omnitruck.chef.io/install.ps1 } | iex; install -project inspec
```
works without any issues on Windows 2012 x64
<img width="752" alt="screen shot 2017-03-07 at 3 28 49 pm" src="https://cloud.githubusercontent.com/assets/1178413/23660888/31928d90-034b-11e7-9272-8b7f1cd199cd.png">

But it fails on Windows 10 x64
<img width="1026" alt="screen shot 2017-03-07 at 3 30 28 pm" src="https://cloud.githubusercontent.com/assets/1178413/23660887/3170b832-034b-11e7-93e2-1dfc619cd6c0.png">

Any ideas what is going wrong? The manual installation of the inspec package from https://downloads.chef.io/inspec/1.16.1 worked without any issues.

**Comment by schisamo** [comment]
Great question @chris-rock, it appears the underlying call `install.ps1` makes to the `/metadata` endpoint returns data as expected:

```
➜  curl "https://omnitruck.chef.io/stable/inspec/metadata?p=windows&pv=10&m=x86_64"
sha1	fb3177121b1241f0559c42b9959f08a7a3283a07
sha256	dbd4ffe7496393d970c42a491f16b070041ea1485c106c725dff7674e5c04947
url	https://packages.chef.io/files/stable/inspec/1.16.1/windows/2012/inspec-1.16.1-1-x64.msi
version	1.16.1
```

Do you mind attempting to install `chef` and `chefdk` on Windows 10 in your test environment, that will give us some more data points. If all three fail that would point to a Windows 10 issue with the underlying PowerShell code of `install.ps1`.

Also looping in @wrightp and @mwrock in case they have ideas.

**Comment by chris-rock** [comment]
I'll tried with `chef` and `chef-dk` on Windows 10, same result:

<img width="1109" alt="screen shot 2017-03-07 at 3 57 24 pm" src="https://cloud.githubusercontent.com/assets/1178413/23662097/c971b48a-034e-11e7-8acd-331fbe0137d2.png">

**Comment by mwrock** [comment]
The best way to debug these issues is to run the installer and point to a log file by adding `/L*V "C:\log\example.log"` to the msiexec call. There will be alot in there but it will definitely say why it is emitting a 1603.

**Comment by chris-rock** [comment]
@mwrock Which part of the script do I need to modify to get that output?

**Comment by mwrock** [comment]
@chris-rock I am assuming (maybe incorrectly) that downloading the msi and running it will also produce an error. So its probably easiest to just download it and then run `msiexec /i msi_file.msi /L*V "C:\log\example.log"`

**Comment by chris-rock** [comment]
Downloading the msi file from chef directly worked without any issues, but it uses the UI. And the script worked perfectly fine on Windows 2012. Is the script working on your Windows 10?

**Comment by mwrock** [comment]
Just tried it @chris-rock and it worked on my win 10 machine. via `. { iwr -useb https://omnitruck.chef.io/install.ps1 } | iex; install -project inspec`.

I have not installed chef-dk for a few releases (shame on me) and I wonder if there might be a bundled inspec conflicting with this inspec on your win 10 system?

**Comment by chris-rock** [comment]
I just figured out what the problem is, I haven't started a Powershell in administrator modus. Once I have a Powershell in administrator mode, the installation works without any issue. Not sure if we can or should handle this error then. e.g. show a proper error message that permissions are missing.
