### ISSUE TITLE
Instalation

### ISSUE THREAD

**Issue by Mikhail42** [chef/omnitruck#214]
Sorry for my bad English. I want to install Chef on my CentOS 7 system. I followed http://gettingstartedwithchef.com/first-steps-with-chef.html and type in terminal
    `sudo curl -L https://www.opscode.com/chef/install.sh | bash`
I don't understand how to solve this problem. 

My full log in terminal:
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 20507  100 20507    0     0   2532      0  0:00:08  0:00:08 --:--:--  6165
el 7 x86_64
Getting information for chef stable  for el...
downloading https://omnitruck-direct.chef.io/stable/chef/metadata?v=&p=el&pv=7&m=x86_64
  to file /tmp/install.sh.7063/metadata.txt
trying wget...
sha1	5e36301f5e751f2a79a8b513831b5bc0b478bbed
sha256	124d34d3a26ce25305899bc93df58aaf4979c5c065adcf1e6487734afb6edf6c
url	https://packages.chef.io/files/stable/chef/12.19.36/el/7/chef-12.19.36-1.el7.x86_64.rpm
version	12.19.36
downloaded metadata file looks valid...
downloading https://packages.chef.io/files/stable/chef/12.19.36/el/7/chef-12.19.36-1.el7.x86_64.rpm
  to file /tmp/install.sh.7063/chef-12.19.36-1.el7.x86_64.rpm
trying wget...
Comparing checksum with sha256sum...

WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING

You are installing an omnibus package without a version pin.  If you are installing
on production servers via an automated process this is DANGEROUS and you will
be upgraded without warning on new releases, even to new major releases.
Letting the version float is only appropriate in desktop, test, development or
CI/CD environments.

WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING

Installing chef 
installing with rpm...
warning: /tmp/install.sh.7063/chef-12.19.36-1.el7.x86_64.rpm: Header V4 DSA/SHA1 Signature, key ID 83ef826a: NOKEY
error: can't create transaction lock on /var/lib/rpm/.rpm.lock (Permission denied)
Installation failed
Version:

**Comment by Mikhail42** [comment]
Also I try use a section "Chef Installation" (https://github.com/chef/chef). 
But I get a next message:

Fetching gem metadata from https://rubygems.org/.........
Fetching version metadata from https://rubygems.org/...
Fetching dependency metadata from https://rubygems.org/..
Fetching https://github.com/rubysec/bundler-audit.git
Fetching https://github.com/chef/ohai.git
Fetching https://github.com/chef/chefstyle.git
Fetching https://github.com/chef/github-changelog-generator
Fetching https://github.com/poise/halite.git
Fetching https://github.com/chef/chef-server
Fetching https://github.com/poise/poise.git
Fetching https://github.com/poise/poise-boiler.git
ohai-13.0.0 requires ruby version >= 2.2.0, which is incompatible with the current version, ruby 2.0.0p648
[mionkin@misha chef]$ ruby --version
ruby 2.4.0p0 (2016-12-24 revision 57164) [x86_64-linux]

**Comment by lamont-granquist** [comment]
```
error: can't create transaction lock on /var/lib/rpm/.rpm.lock (Permission denied)
```

some other program is holding a lock on the rpm database.  check the process table for anything matching 'rpm' or 'yum 'to track it down.  otherwise just wait a bit, or i suppose you could reboot.

**Comment by thommay** [comment]
unfortunately, you've run sudo on the wrong bit, you need to do:
```
curl -L https://www.opscode.com/chef/install.sh | sudo bash
```
for this to work.

**Comment by tas50** [comment]
As @thommay mentioned this error is due to running sudo on the curl portion instead of the bash portion. We pipe the file to bash to perform the install and that's where the elevated permissions are required.
