### ISSUE TITLE
Changes at Fastly causes PowerShell script to fail

### ISSUE THREAD

**Issue by adhodgson1** [chef/omnitruck#249]
Hi,

Running this command:

 iex (irm https://omnitruck.chef.io/install.ps1); Install-Project -Project chefdk -channel stable

From PowerShell (either directly or via a CI script) gives the following error:

irm : The request was aborted: Could not create SSL/TLS secure channel.
At line:1 char:7
+  iex (irm https://omnitruck.chef.io/install.ps1); Install-Project -Project
chefd ...
+       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:Htt
   pWebRequest) [Invoke-RestMethod], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShe
   ll.Commands.InvokeRestMethodCommand

After investigation the fix is to enable TLS 1.2 support:

[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12

This has to be done once per session.

**Comment by adhodgson1** [comment]
This has broken Kitchen as well:

 50c:\opscode\chefdk\bin\chef.bat exec kitchen verify
 51-----> Starting Kitchen (v1.16.0)
 52-----> Creating <...>...
 53       Resetting instance state with command: exit 0
 54       Finished creating <...> (0m5.69s).
 55-----> Converging <...>...
 56$$$$$$ Running legacy converge for 'Proxy' Driver
 57       Preparing files for transfer
 58       Preparing dna.json
 59       Resolving cookbook dependencies with Berkshelf 5.6.4...
 60       Removing non-cookbook files before transfer
 61       Preparing validation.pem
 62       Preparing client.rb
 63-----> Installing Chef Omnibus (12.19)
 64       There was an error: 
 65       	Exception calling "DownloadString" with "1" argument(s): "The request was aborted: Could not create SSL/TLS secure channel."
 66       	The request was aborted: Could not create SSL/TLS secure channel.

**Comment by takesson** [comment]
Saw this issue yesterday. Seems to be working today. Anyone having the same experience?

**Comment by thommay** [comment]
We've moved to a new Fastly endpoint that supports TLS 1.0 and 1.1, so the problem ought to be resolved.
