### ISSUE TITLE
Unable to retrieve a valid package

### ISSUE THREAD

**Issue by dylan-colaco** [chef/omnitruck#264]
OS: CentOS 7.2
When trying to boostrap a node with chef:

-----> Installing Chef Omnibus (-v 12)
downloading https://omnitruck-direct.chef.io/chef/install.sh
  to file /tmp/install.sh.9544/install.sh
trying wget...
el 7 x86_64
Getting information for chef stable 12 for el...
downloading https://omnitruck-direct.chef.io/stable/chef/metadata?v=12&p=el&pv=7&m=x86_64
  to file /tmp/install.sh.9549/metadata.txt
trying wget...
trying curl...
trying perl...
trying python...
sha1	2d78a2f463c0d3d7ed867a50a9460650b196e251
sha256	b2b8c16b92d65d003ee07f1f30a456b573a8cdddf6ba66e4afba42d44060492a
url	https://packages.chef.io/files/stable/chef/12.20.3/el/7/chef-12.20.3-1.el7.x86_64.rpm
version	12.20.3
downloaded metadata file looks valid...
downloading https://packages.chef.io/files/stable/chef/12.20.3/el/7/chef-12.20.3-1.el7.x86_64.rpm
  to file /tmp/install.sh.9549/chef-12.20.3-1.el7.x86_64.rpm
trying wget...
trying curl...
trying perl...
trying python...
Unable to retrieve a valid package!
Version: 12

Please file a Bug Report at https://github.com/chef/omnitruck/issues/new
Alternatively, feel free to open a Support Ticket at https://www.chef.io/support/tickets
More Chef support resources can be found at https://www.chef.io/support

**Comment by jtimberman** [comment]
Hello,

I'm sorry that we never followed up on this issue. As it is quite old, and there have been many changes to the products and operating systems involved, I'm going to close this issue as reproducing it would be difficult, if not impossible.

Cheers
Joshua
