### ISSUE TITLE
curl -L https://omnitruck.chef.io/install.sh | sudo bash  FAILS

### ISSUE THREAD

**Issue by dimon415** [chef/omnitruck#265]
# curl -L https://omnitruck.chef.io/install.sh | sudo bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 20500  100 20500    0     0  36671      0 --:--:-- --:--:-- --:--:-- 50492
el 6 x86_64
Getting information for chef stable  for el...
downloading https://omnitruck.chef.io/stable/chef/metadata?v=&p=el&pv=6&m=x86_64
  to file /tmp/install.sh.16893/metadata.txt
trying wget...
trying curl...
grep: /tmp/install.sh.16893/stderr: No such file or directory
trying perl...
trying python...
Unable to retrieve a valid package!
Version:

Please file a Bug Report at https://github.com/chef/omnitruck/issues/new
Alternatively, feel free to open a Support Ticket at https://www.chef.io/support/tickets
More Chef support resources can be found at https://www.chef.io/support

Please include as many details about the problem as possible i.e., how to reproduce
the problem (if possible), type of the Operating System and its version, etc.,
and any other relevant details that might help us with troubleshooting.

Metadata URL: https://omnitruck.chef.io/stable/chef/metadata?v=&p=el&pv=6&m=x86_64
\nDEBUG OUTPUT FOLLOWS:\n\nSTDERR from wget:\n\n--2017-06-21 08:26:26--  https://omnitruck.chef.io/stable/chef/metadata?v=&p=el&pv=6&m=x86_64
Resolving omnitruck.chef.io... 151.101.48.65
Connecting to omnitruck.chef.io|151.101.48.65|:443... failed: Connection timed out.
Retrying.

**Comment by zerolaser** [comment]
any update on if this bug is fixed ?

**Comment by jtimberman** [comment]
Hello,

I'm sorry that we never followed up on this issue. As it is quite old, and there have been many changes to the products and operating systems involved, I'm closing this out. 

Cheers
Joshua
