### ISSUE TITLE
Does not detect curl python pearl or wget on CENTOS 7

### ISSUE THREAD

**Issue by DMEvanCT** [chef/omnitruck#282]
-----> Installing Chef Omnibus (-v 12)
downloading https://omnitruck-direct.chef.io/chef/install.sh
  to file /tmp/install.sh.2186/install.sh
trying wget...
trying curl...
trying perl...
trying python...
>>>>>> wget, curl, fetch, perl, or python not found on this instance.
\nDEBUG OUTPUT FOLLOWS:\n\nSTDERR from wget:\n\n--2017-07-21 05:12:47--  https://omnitruck-direct.chef.io/chef/install.sh
Resolving omnitruck-direct.chef.io (omnitruck-direct.chef.io)... failed: Name or service not known.
wget: unable to resolve host address ‘omnitruck-direct.chef.io’\n\nSTDERR from curl:\n\n\n\nSTDERR from perl:\n\nCan't locate LWP/Simple.pm in @INC (@INC contains: /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .) at -e line 1.
BEGIN failed--compilation aborted at -e line 1.\n\nSTDERR from python:\n\nTraceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib64/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib64/python2.7/urllib2.py", line 431, in open
    response = self._open(req, data)
  File "/usr/lib64/python2.7/urllib2.py", line 449, in _open
    '_open', req)
  File "/usr/lib64/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 1258, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/usr/lib64/python2.7/urllib2.py", line 1214, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [Errno -2] Name or service not known>\n
Starting the first Chef Client run...

**Comment by jtimberman** [comment]
Hello,

I'm sorry that we never followed up on this issue!

It looks like the system was unable to resolve the host `omnitruck-direct.chef.io`. Please ensure that basic OS utilities like `host` work. For example, it should resolve something like this:

```
# host omnitruck.chef.io
omnitruck.chef.io is an alias for f4.shared.global.fastly.net.
f4.shared.global.fastly.net has address 151.101.2.110
f4.shared.global.fastly.net has address 151.101.66.110
f4.shared.global.fastly.net has address 151.101.130.110
f4.shared.global.fastly.net has address 151.101.194.110

# host omnitruck-direct.chef.io
omnitruck-direct.chef.io is an alias for omnitruck-elb-1344766176.us-west-2.elb.amazonaws.com.
omnitruck-elb-1344766176.us-west-2.elb.amazonaws.com has address 54.69.103.199
omnitruck-elb-1344766176.us-west-2.elb.amazonaws.com has address 52.27.62.2
omnitruck-elb-1344766176.us-west-2.elb.amazonaws.com has address 34.214.216.30
```

Cheers
Joshua
