### ISSUE TITLE
suse failed to download chef

### ISSUE THREAD

**Issue by zackyaz** [chef/omnitruck#310]
when running the kitchen  got the following error

 Installing Chef Omnibus (12)
       Downloading https://omnitruck.chef.io/install.sh to file /tmp/install.sh
       Trying wget...
       Download complete.
       sles 12 x86_64
       Getting information for chef stable 12 for sles...
       downloading https://omnitruck.chef.io/stable/chef/metadata?v=12&p=sles&pv=12&m=x86_64
         to file /tmp/install.sh.10778/metadata.txt
       trying wget...
       trying curl...
       <h1>Internal Server Error</h1><h1>Internal Server Error</h1><h1>Internal Server Error</h1><h1>Internal Server Error</h1><h1>Internal Server Error</h1><h1>Internal Server Error</h1>
       downloaded metadata file is corrupted or an uncaught error was encountered in downloading the file...
       Version: 12

**Comment by wrightp** [comment]
fixed
