### ISSUE TITLE
Package checksum mismatch!

### ISSUE THREAD

**Issue by ashutoshnarayan** [chef/omnitruck#315]
I was bootstrapping a node and while doing so I encountered an error saying Package checksum mismatch! I then verified the metadata.txt file on target node and found that sha256sum actually showed different values: 
`# cat metadata.txt 
sha1	d3d26412b6304c92f72749d00e62e0191ceada05
sha256	fe051b504856a74ccce1fd23ff92c296506cb8292a3933c71069ae915e7a4a00
url	https://packages.chef.io/files/stable/chef/13.3.42/el/7/chef-13.3.42-1.el7.x86_64.rpm`

`sha256sum chef-13.3.42-1.el7.x86_64.rpm
54272f366c34abd166daa8527038e6399d9972f15575a805c5bc5c10cda044cc  chef-13.3.42-1.el7.x86_64.rpm`

Because of this chef-client installation was failing. 
`Starting the first Chef Client run...
sh: line 284: chef-client: command not found`

Please look at it.

**Comment by wrightp** [comment]
Downloaded the file using the same url.
Ran `shasum -a 256 chef-13.3.42-1.el7.x86_64.rpm` and got `fe051b504856a74ccce1fd23ff92c296506cb8292a3933c71069ae915e7a4a00`

Also verified the checksum in the repository. It is correct.
