### ISSUE TITLE
Installing local instance

### ISSUE THREAD

**Issue by SDBrett** [chef/omnitruck#320]
I am trying to install Omnitruck as a local instance, to provide a local repository to source the chef-client from. After running bundle install from the root directory, I attempt to run bundle exec ./poller -e development.

I get no output, just returns to a prompt

As there was a ./poller points to ./config/config.yml I have copied the example file dropping the .example, this made no difference.

Looking for some assistance on how I can get omnitruck running on an internal host.

**Comment by scotthain** [comment]
@SDBrett it's a little ruby bug, you can simply run `bundle exec poller -e development` and it should work! I've also added a comparison fix so either should work in the future here: https://github.com/chef/omnitruck/pull/321

**Comment by SDBrett** [comment]
Thanks mate, dropping the ./ worked a treat :)
