### ISSUE TITLE
Building with habitat

### ISSUE THREAD

**Issue by SDBrett** [chef/omnitruck#322]
To help with delivery of the Omnibus on to an internal server, I'm trying to go through the build steps with Habitat and export to a docker image.

From the README.md in /habitat, it states to use /scripts/hab-it.sh to perform the build. 
When attempting this I end up with the error. Full log below
★ Install of core/scaffolding-ruby/0.8.4/20170901221322 complete with 9 new packages installed.
   omnitruck-app: Resolved scaffolding dependency 'core/scaffolding-ruby' to /hab/pkgs/core/scaffolding-ruby/0.8.4/20170901221322
   omnitruck-app: Loading Scaffolding /hab/pkgs/core/scaffolding-ruby/0.8.4/20170901221322/lib/scaffolding.sh
ERROR: Ruby Scaffolding cannot find Gemfile in the root directory

The issue appears to be with build habitat, the rest of the build items work ok.

`[1][default:/src:0]# ./scripts/hab-it
   : Loading /src/habitat/plan.sh
cat: /src/habitat/.ruby-version: No such file or directory
   omnitruck-app: Plan loaded
   omnitruck-app: Validating plan metadata
   omnitruck-app: hab-plan-build setup
   omnitruck-app: Writing pre_build file
   omnitruck-app: Using HAB_BIN=/hab/pkgs/core/hab/0.30.2/20170822232349/bin/hab for installs, signing, and hashing
   omnitruck-app: Resolving scaffolding dependencies
» Installing core/scaffolding-ruby from channel 'stable'
☛ Verifying core/scaffolding-ruby/0.8.4/20170901221322
→ Using core/acl/2.2.52/20170513213108
→ Using core/attr/2.4.47/20170513213059
→ Using core/binutils/2.25.1/20170513201927
☛ Verifying core/bundler/1.15.4/20170830210853
→ Using core/busybox-static/1.24.2/20170513215502
→ Using core/cacerts/2017.01.18/20170513215104
→ Using core/coreutils/8.25/20170513213226
→ Using core/gcc-libs/5.2.0/20170513212920
☛ Verifying core/gcc/5.2.0/20170513202244
→ Using core/glibc/2.22/20170513201042
→ Using core/gmp/6.1.0/20170513202112
→ Using core/grep/2.22/20170513213444
→ Using core/libcap/2.24/20170513213120
☛ Verifying core/libffi/3.2.1/20170514003538
☛ Verifying core/libmpc/1.0.3/20170513202228
☛ Verifying core/libtool/2.4.6/20170513213706
☛ Verifying core/libyaml/0.1.6/20170514013335
→ Using core/linux-headers/4.3/20170513200956
→ Using core/make/4.2.1/20170513214620
→ Using core/mpfr/3.1.4/20170513202156
→ Using core/ncurses/6.0/20170513213009
→ Using core/openssl/1.0.2j/20170513215106
→ Using core/pcre/8.38/20170513213423
☛ Verifying core/pkg-config/0.29/20170513212944
→ Using core/readline/6.3.8/20170513213506
→ Using core/rq/0.9.2/20170612005822
☛ Verifying core/ruby/2.4.1/20170514013342
→ Using core/sed/4.2.2/20170513213123
→ Using core/tar/1.29/20170513213607
→ Using core/zlib/1.2.8/20170513201911
✓ Installed core/bundler/1.15.4/20170830210853
✓ Installed core/gcc/5.2.0/20170513202244
✓ Installed core/libffi/3.2.1/20170514003538
✓ Installed core/libmpc/1.0.3/20170513202228
✓ Installed core/libtool/2.4.6/20170513213706
✓ Installed core/libyaml/0.1.6/20170514013335
✓ Installed core/pkg-config/0.29/20170513212944
✓ Installed core/ruby/2.4.1/20170514013342
✓ Installed core/scaffolding-ruby/0.8.4/20170901221322
★ Install of core/scaffolding-ruby/0.8.4/20170901221322 complete with 9 new packages installed.
   omnitruck-app: Resolved scaffolding dependency 'core/scaffolding-ruby' to /hab/pkgs/core/scaffolding-ruby/0.8.4/20170901221322
   omnitruck-app: Loading Scaffolding /hab/pkgs/core/scaffolding-ruby/0.8.4/20170901221322/lib/scaffolding.sh
ERROR: Ruby Scaffolding cannot find Gemfile in the root directory`

**Comment by jtimberman** [comment]
Looks like this was addressed in #321.
