### ISSUE TITLE
error while bootstraping node.

### ISSUE THREAD

**Issue by shruti23** [chef/omnitruck#345]
logs 
---------------------------------------------------------------------------------------------

10.186.210.89 installing with rpm...
10.186.210.89 warning: /tmp/install.sh.77771/chef-12.21.31-1.el7.x86_64.rpm: Header V4 DSA/SHA1 Signature, key ID 83ef826a: NOKEY
10.186.210.89 error: can't create transaction lock on /var/lib/rpm/.rpm.lock (Permission denied)
10.186.210.89 Installation failed
10.186.210.89 Version: 12
10.186.210.89
10.186.210.89 Please file a Bug Report at https://github.com/chef/omnitruck/issues/new
10.186.210.89 Alternatively, feel free to open a Support Ticket at https://www.chef.io/support/tickets
10.186.210.89 More Chef support resources can be found at https://www.chef.io/support
10.186.210.89
10.186.210.89 Please include as many details about the problem as possible i.e., how to reproduce
10.186.210.89 the problem (if possible), type of the Operating System and its version, etc.,
10.186.210.89 and any other relevant details that might help us with troubleshooting.
10.186.210.89
10.186.210.89 mkdir: cannot create directory ‘/etc/chef’: Permission denied
10.186.210.89 sh: line 178: /etc/chef/client.pem: No such file or directory
10.186.210.89 chmod: cannot access ‘/etc/chef/client.pem’: No such file or directory
10.186.210.89 mkdir: cannot create directory ‘/etc/chef’: Permission denied
10.186.210.89 sh: line 213: /etc/chef/trusted_certs/gz-zu2chmplv001.glblcloud.ad.pwcinternal.com.crt: No such file or directory
10.186.210.89 sh: line 244: /etc/chef/client.rb: No such file or directory
10.186.210.89 sh: line 253: /etc/chef/first-boot.json: No such file or directory
10.186.210.89 Starting the first Chef Client run...
10.186.210.89 sh: line 260: chef-client: command not found

**Comment by thommay** [comment]
You appear not to have used sudo or escalated privileges to install software. This is not a bug in our software.
