### ISSUE TITLE
checksum mismatch

### ISSUE THREAD

**Issue by glenvillef** [chef/omnitruck#347]
Hi 
Im doing a kitchen converge on the following repo for CentOS 6.7 and 6.8: 
https://github.com/vkhatri/chef-metricbeat

I have the below issue happening when trying to checksum the packages downloaded from omnitruck.chef.io. Believe its to do with your metadata.txt file. 

-----> Installing Chef Omnibus (install only if missing)
       Downloading https://omnitruck.chef.io/install.sh to file /tmp/install.sh
       Trying wget...
       Download complete.
       el 6 x86_64
       Getting information for chef stable  for el...
       downloading https://omnitruck.chef.io/stable/chef/metadata?v=&p=el&pv=6&m=x86_64
         to file /tmp/install.sh.2699/metadata.txt
       trying wget...
       sha1	96ff3d8d31d0fd3be442364bd76b38425396b2d8
       sha256	8a6adbb5e7f16a8771c0556615b7cd77620d38d11c25b19cb2e638dbd4dc7390
       url	https://packages.chef.io/files/stable/chef/13.8.0/el/6/chef-13.8.0-1.el6.x86_64.rpm
       version	13.8.0
       downloaded metadata file looks valid...
       /tmp/omnibus/cache/chef-13.8.0-1.el6.x86_64.rpm exists
       Comparing checksum with sha256sum...
       Package checksum mismatch!

----------------------------------------------------------------
Result when doing a checksum on the downloaded packages: 
[root@default-centos-68 tmp]# sha1sum /tmp/omnibus/cache/chef-13.8.0-1.el6.x86_64.rpm
85395c3035fe24174f9f2c96ef1592af7a524a73  /tmp/omnibus/cache/chef-13.8.0-1.el6.x86_64.rpm

[root@default-centos-68 tmp]# sha256sum /tmp/omnibus/cache/chef-13.8.0-1.el6.x86_64.rpm 
ee70db77ff048dfecde5cd92806912c5f05b47136fe731cd7ac0752eba429a70  /tmp/omnibus/cache/chef-13.8.0-1.el6.x86_64.rpm

**Comment by glenvillef** [comment]
Any feedback on this issue?

**Comment by sjtindell** [comment]
Same issue later version of chefdk.

**Comment by racorretjer** [comment]
Same issue with a later version of everything:

-----> Starting Kitchen (v1.22.0)
-----> Converging <default-centos-7>...
       Preparing files for transfer
       Preparing dna.json
       Resolving cookbook dependencies with Berkshelf 7.0.4...
       Removing non-cookbook files before transfer
       Preparing validation.pem
       Preparing client.rb
-----> Installing Chef Omnibus (install only if missing)
       Downloading https://omnitruck.chef.io/install.sh to file /tmp/install.sh
       Trying wget...
       Download complete.
       el 7 x86_64
       Getting information for chef stable  for el...
       downloading https://omnitruck.chef.io/stable/chef/metadata?v=&p=el&pv=7&m=x86_64
         to file /tmp/install.sh.3091/metadata.txt
       trying wget...
       sha1	bf0bd662c5b46d81418c943ac4bc6b84c095aa9c
       sha256	abdb676a8d55fc9807b4eabe5313c54d3946977d7ae3eecd7303cd388b04042a
       url	https://packages.chef.io/files/stable/chef/14.2.0/el/7/chef-14.2.0-1.el7.x86_64.rpm
       version	14.2.0
       downloaded metadata file looks valid...
       /tmp/omnibus/cache/chef-14.2.0-1.el7.x86_64.rpm exists
       Comparing checksum with sha256sum...
       Package checksum mismatch!
       Version: 
       
       Please file a Bug Report at https://github.com/chef/omnitruck/issues/new
       Alternatively, feel free to open a Support Ticket at https://www.chef.io/support/tickets
       More Chef support resources can be found at https://www.chef.io/support
       
       Please include as many details about the problem as possible i.e., how to reproduce
       the problem (if possible), type of the Operating System and its version, etc.,
       and any other relevant details that might help us with troubleshooting.

**Comment by racorretjer** [comment]
A temporary work around is to delete the tmp file and try again. I blame it on slow internet - I may have lost a packet or two.

**Comment by jtimberman** [comment]
Hello,

I'm sorry that we never followed up on this issue. It's hard to say whether this is still an issue, as I'm not aware of it being widely reported at this time. If it's still a problem with the latest version of chef/chefk, test-kitchen, and the kitchen images of the operating systems you're using, please open a new issue.

Cheers
Joshua

**Comment by anugoen4** [comment]
Deleting contents of cache folder present in .knife folder should work.
