### ISSUE TITLE
chef-client not installing in centos7

### ISSUE THREAD

**Issue by narisimhareddy** [chef/omnitruck#348]
these are the errors for me while doing power shell

 Please include as many details about the problem as possible i.e., how to reprot the problem (if possible), type of the Operating System and its version, etc and any other relevant details that might help us with troubleshooting.

 mkdir: cannot create directory ‘/etc/chef’: Permission denied
 sh: line 178: /etc/chef/client.pem: No such file or directory
 chmod: cannot access ‘/etc/chef/client.pem’: No such file or directory
 sh: line 214: /etc/chef/client.rb: No such file or directory
 sh: line 222: /etc/chef/first-boot.json: No such file or directory
 Starting the first Chef Client run...
sh: line 229: chef-client: command not found

**Comment by thommay** [comment]
You need to run the command with root privileges on a linux machine.
