### ISSUE TITLE
error: cannot open Packages index using db5 - Permission denied (13)

### ISSUE THREAD

**Issue by mithuncus** [chef/omnitruck#355]
Hi There,

When I am running bootstrap command , I am able to see the update in the chef-server. But Its not able to install the chef software at chef-client. I was getting error as below Please find it.

-----> Installing Chef Omnibus (-v 13)
192.160.0.0 downloading https://omnitruck-direct.chef.io/chef/install.sh
192.160.0.0   to file /tmp/install.sh.22355/install.sh
192.160.0.0 trying wget...
192.160.0.0 el 7 x86_64
192.160.0.0 Getting information for chef stable 13 for el...
192.160.0.0 downloading https://omnitruck-direct.chef.io/stable/chef/metadata?v=13&p=el&pv=7&m=x86_64
192.160.0.0   to file /tmp/install.sh.22378/metadata.txt
192.160.0.0 trying wget...
192.160.0.0 sha1        76d7d05e00156bd9203f3684ee07d611715bfa65
192.160.0.0 sha256      959eac2fb57a5b7f53576edbcb63c3c4a723673673d48c1cd8d46f6c6da9a9b1
192.160.0.0 url https://packages.chef.io/files/stable/chef/13.9.1/el/7/chef-13.9.1-1.el7.x86_64.rpm
192.160.0.0 version     13.9.1
192.160.0.0 downloaded metadata file looks valid...
192.160.0.0 downloading https://packages.chef.io/files/stable/chef/13.9.1/el/7/chef-13.9.1-1.el7.x86_64.rpm
192.160.0.0   to file /tmp/install.sh.22378/chef-13.9.1-1.el7.x86_64.rpm
192.160.0.0 trying wget...
192.160.0.0 Comparing checksum with sha256sum...
192.160.0.0 Installing chef 13
192.160.0.0 installing with rpm...
192.160.0.0 warning: /tmp/install.sh.22378/chef-13.9.1-1.el7.x86_64.rpm: Header V4 DSA/SHA1 Signature, key ID 83ef826a: NOKEY
192.160.0.0 error: cannot open Packages index using db5 - Permission denied (13)
192.160.0.0 error: cannot open Packages database in /var/lib/rpm
192.160.0.0 Installation failed
192.160.0.0 Version: 13
192.160.0.0
192.160.0.0 Please file a Bug Report at https://github.com/chef/omnitruck/issues/new
192.160.0.0 Alternatively, feel free to open a Support Ticket at https://www.chef.io/support/tickets
192.160.0.0 More Chef support resources can be found at https://www.chef.io/support
192.160.0.0
192.160.0.0 Please include as many details about the problem as possible i.e., how to reproduce
192.160.0.0 the problem (if possible), type of the Operating System and its version, etc.,
192.160.0.0 and any other relevant details that might help us with troubleshooting.
192.160.0.0
192.160.0.0 Starting the first Chef Client run...
192.160.0.0 sh: line 229: chef-client: command not found

I am using centos on virtualbox. 
Linux version 3.10.0-693.21.1.el7.x86_64 (builder@kbuilder.dev.centos.org) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-16) (GCC) ) #1 SMP Wed Mar 7 19:03:37 UTC 2018

I have run the below commands 
  sudo restorecon -R -v /var/lib/rpm
   chef client
   cd /var/lib/rpm/
   sudo mv __db.00* /tmp
   rpm --rebuilddb
   sudo rpm --rebuilddb
   cd /var/lib/rpm
   sudo rm -f __*
   rpm --rebuilddb
   rpm -vv --rebuilddb
    sudo rpm -vv --rebuilddb
    rpm -qa
   /usr/lib/rpm/rpmdb_stat -h /var/lib/rpm -CA 

I am still facing the same issue  error: cannot open Packages index using db5 - Permission denied (13)
Please Let me know any possible solution . Thanks in advance .

**Comment by thommay** [comment]
It looks as though you're not running the install script as root?

**Comment by jtimberman** [comment]
If you're using `knife bootstrap` be sure you're either using the `root` user, or the `--sudo` argument to the command.
