### ISSUE TITLE
Package checksum mismatch!

### ISSUE THREAD

**Issue by rorys32** [chef/omnitruck#356]
After upgrading chefdk to the latest version. I am getting a Package checksum mismatch error.
Version Details:
chef --version
Chef Development Kit Version: 3.0.36
chef-client version: 14.1.12
delivery version: master (7206afaf4cf29a17d2144bb39c55b7212cfafcc7)
berks version: 7.0.2
kitchen version: 1.21.2
inspec version: 2.1.72

Test Kitchen log snippet:
[2018-05-24T09:32:28.740234 #35452]  INFO -- default-centos-7: trying wget...
I, [2018-05-24T09:32:29.894762 #35452]  INFO -- default-centos-7: sha1	f75164aae67118ddda8d89b0e9030c06be92c967
I, [2018-05-24T09:32:29.894824 #35452]  INFO -- default-centos-7: sha256	83da7d8de5f2e93b3706d97b0f8f9837a5f3c2da01d77419645152e0ad9e1f41
I, [2018-05-24T09:32:29.894844 #35452]  INFO -- default-centos-7: url	https://packages.chef.io/files/stable/chef/14.1.12/el/7/chef-14.1.12-1.el7.x86_64.rpm
I, [2018-05-24T09:32:29.894861 #35452]  INFO -- default-centos-7: version	14.1.12
I, [2018-05-24T09:32:29.896632 #35452]  INFO -- default-centos-7: downloaded metadata file looks valid...
I, [2018-05-24T09:32:29.905091 #35452]  INFO -- default-centos-7: /tmp/omnibus/cache/chef-14.1.12-1.el7.x86_64.rpm exists
I, [2018-05-24T09:32:29.905142 #35452]  INFO -- default-centos-7: Comparing checksum with sha256sum...
I, [2018-05-24T09:32:30.172551 #35452]  INFO -- default-centos-7: Package checksum mismatch!
I, [2018-05-24T09:32:30.172605 #35452]  INFO -- default-centos-7: Version: 
I, [2018-05-24T09:32:30.172621 #35452]  INFO -- default-centos-7:

**Comment by darkn3rd** [comment]
Documented 100% reproducible case using Test Kitchen 1.22.0 installed with ChefDK 3.1.0: 

* https://github.com/test-kitchen/test-kitchen/issues/1447
