### ISSUE TITLE
Unable to retrieve a valid package when Installing Chef latest Omnibus package

### ISSUE THREAD

**Issue by rahulgoenka** [chef/omnitruck#357]
Hi I am not able to do a successful vibrant up , when doing this it is throwing this error.

default] GuestAdditions 5.2.12 running --- OK.
==> default: Checking for guest additions in VM...
==> default: Setting hostname...
==> default: Configuring and enabling network interfaces...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
==> default: Mounting shared folders...
    default: /vagrant => /Users/rahul.goenka/is-quiz-vagrant
    default: /tmp/vagrant-chef/f5f6b598ed705d21d9c7ea2e788f4977/roles => /Users/rahul.goenka/is-quiz-vagrant/roles
    default: /tmp/vagrant-chef/35597fcad219a87043ed7689d3719fe1/cookbooks => /Users/rahul.goenka/is-quiz-vagrant/berks-cookbooks
    default: /tmp/vagrant-chef/cf4d3d57e5a8a0623a8288950be6b709/cookbooks => /Users/rahul.goenka/is-quiz-vagrant/site-cookbooks
==> default: Installing Chef latest Omnibus package...
==> default: el 6 x86_64
==> default: setting https_proxy: http://dev-proxy.db.rakuten.co.jp:9502
==> default: setting http_proxy: http://dev-proxy.db.rakuten.co.jp:9502
==> default: Getting information for chef stable latest for el...
==> default: downloading https://omnitruck-direct.chef.io/stable/chef/metadata?v=latest&p=el&pv=6&m=x86_64
==> default:   to file /tmp/install.sh.4621/metadata.txt
==> default: trying wget...
==> default: trying curl...
==> default: grep: 
==> default: /tmp/install.sh.4621/stderr
==> default: : No such file or directory

==> default: trying perl...
==> default: trying python...
==> default: Unable to retrieve a valid package!
==> default: Version: latest
==> default: 

Metadata URL: https://omnitruck-direct.chef.io/stable/chef/metadata?v=latest&p=el&pv=6&m=x86_64
\nDEBUG OUTPUT FOLLOWS:\n\nSTDERR from wget:\n\n--2018-06-07 19:09:04--  https://omnitruck-direct.chef.io/stable/chef/metadata?v=latest&p=el&pv=6&m=x86_64
Resolving dev-proxy.db.rakuten.co.jp... failed: Name or service not known.
wget: unable to resolve host address “dev-proxy.db.rakuten.co.jp”\n\nSTDERR from perl:\n\n500 Can't connect to dev-proxy.db.rakuten.co.jp:9502 (Bad hostname 'dev-proxy.db.rakuten.co.jp') <URL:https://omnitruck-direct.chef.io/stable/chef/metadata?v=latest&p=el&pv=6&m=x86_64>\n\nSTDERR from python:\n\nTraceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib64/python2.6/urllib2.py", line 126, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/lib64/python2.6/urllib2.py", line 391, in open
    response = self._open(req, data)
  File "/usr/lib64/python2.6/urllib2.py", line 409, in _open
    '_open', req)
  File "/usr/lib64/python2.6/urllib2.py", line 369, in _call_chain
    result = func(*args)
  File "/usr/lib64/python2.6/urllib2.py", line 1198, in https_open
    return self.do_open(httplib.HTTPSConnection, req)
  File "/usr/lib64/python2.6/urllib2.py", line 1165, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [Errno -2] Name or service not known>\n

Host OS  : MAC OS X Version 10.12.6
Guest OS : Cent OS 6.7 x86_64
Vagrant 2.1.1
Chef Development Kit Version: 3.0.36
chef-client version: 14.1.12
delivery version: master (7206afaf4cf29a17d2144bb39c55b7212cfafcc7)
berks version: 7.0.2
kitchen version: 1.21.2
inspec version: 2.1.72

**Comment by tduffield** [comment]
It looks like your machine is having trouble connecting to your proxy. 

```
500 Can't connect to dev-proxy.db.rakuten.co.jp:9502 (Bad hostname 'dev-proxy.db.rakuten.co.jp')
```

You may need to double check your VM settings to make sure your proxy information is being passed correctly.
