### ISSUE TITLE
unable to install chef dk in fedora 27

### ISSUE THREAD

**Issue by villival** [chef/omnitruck#358]
curl https://omnitruck.chef.io/install.sh | bash -s -- -P chefdk -c stable -v 2.5.3
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 23429  100 23429    0     0  23429      0  0:00:01 --:--:--  0:00:01 23475
el 6 x86_64
Getting information for chefdk stable 2.5.3 for el...
downloading https://omnitruck.chef.io/stable/chefdk/metadata?v=2.5.3&p=el&pv=6&m=x86_64
  to file /tmp/install.sh.8082/metadata.txt
trying wget...
sha1	0fc5d896c881df5f9a117fdb8a566cfffbd174f6
sha256	79a9e4fc30e0d1b018ae8b1be4a1a77d7a4ab5ea8ff9b94cf451b8c4c9522821
url	https://packages.chef.io/files/stable/chefdk/2.5.3/el/6/chefdk-2.5.3-1.el6.x86_64.rpm
version	2.5.3
downloaded metadata file looks valid...
downloading https://packages.chef.io/files/stable/chefdk/2.5.3/el/6/chefdk-2.5.3-1.el6.x86_64.rpm
  to file /tmp/install.sh.8082/chefdk-2.5.3-1.el6.x86_64.rpm
trying wget...
Comparing checksum with sha256sum...
Installing chefdk 2.5.3
installing with rpm...
warning: /tmp/install.sh.8082/chefdk-2.5.3-1.el6.x86_64.rpm: Header V4 DSA/SHA1 Signature, key ID 83ef826a: NOKEY
error: can't create transaction lock on /var/lib/rpm/.rpm.lock (Inappropriate ioctl for device)
Installation failed
Version: 2.5.3

**Comment by thommay** [comment]
You need to use sudo (or whatever process you use to get elevated privileges) to install packages.
