### ISSUE TITLE
Unable to install Chef on my Mac

### ISSUE THREAD

**Issue by ravisingh3** [chef/omnitruck#361]
Unable to install chef on my Mac due to error- no mountable filesystems. Other softwares are working fine. Need help to install chef on my system.

curl -L https://www.chef.io/chef/install.sh | sudo bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 23436  100 23436    0     0  15619      0  0:00:01  0:00:01 --:--:-- 15613Password:

mac_os_x 10.13 x86_64
Getting information for chef stable  for mac_os_x...
downloading https://omnitruck-direct.chef.io/stable/chef/metadata?v=&p=mac_os_x&pv=10.13&m=x86_64
  to file /tmp/install.sh.8196/metadata.txt
trying wget...
sha1	0a822514c08f76187def2ecdf594c51e6826b350
sha256	ee9520efd059a1c288e1a4a7e827f203c6ba02fa46c767939c037df484196063
url	https://packages.chef.io/files/stable/chef/14.2.0/mac_os_x/10.13/chef-14.2.0-1.dmg
version	14.2.0
downloaded metadata file looks valid...
downloading https://packages.chef.io/files/stable/chef/14.2.0/mac_os_x/10.13/chef-14.2.0-1.dmg
  to file /tmp/install.sh.8196/chef-14.2.0-1.dmg
trying wget...
Comparing checksum with shasum...

WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING

You are installing an omnibus package without a version pin.  If you are installing
on production servers via an automated process this is DANGEROUS and you will
be upgraded without warning on new releases, even to new major releases.
Letting the version float is only appropriate in desktop, test, development or
CI/CD environments.

WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING

Installing chef
installing dmg file...
Checksumming Protective Master Boot Record (MBR : 0)…
Protective Master Boot Record (MBR :: verified   CRC32 $A63E199D
Checksumming GPT Header (Primary GPT Header : 1)…
 GPT Header (Primary GPT Header : 1): verified   CRC32 $D37303F8
Checksumming GPT Partition Data (Primary GPT Table : 2)…
GPT Partition Data (Primary GPT Tabl: verified   CRC32 $5FA0C72A
Checksumming  (Apple_Free : 3)…
                    (Apple_Free : 3): verified   CRC32 $00000000
Checksumming disk image (Apple_HFS : 4)…
..........................................................................................................................................................................................................
          disk image (Apple_HFS : 4): verified   CRC32 $35DAE422
Checksumming  (Apple_Free : 5)…
                    (Apple_Free : 5): verified   CRC32 $00000000
Checksumming GPT Partition Data (Backup GPT Table : 6)…
GPT Partition Data (Backup GPT Table: verified   CRC32 $5FA0C72A
Checksumming GPT Header (Backup GPT Header : 7)…
  GPT Header (Backup GPT Header : 7): verified   CRC32 $4CBE5C56
verified   CRC32 $EA9E03C4
hdiutil: attach failed - no mountable file systems
installer: invalid option /
Usage: installer [-help] [-dominfo] [-volinfo] [-pkginfo] [-allowUntrusted] [-dumplog]
                 [-verbose | -verboseR] [-vers] [-config] [-plist]
                 [-file <pathToFile>] [-lang <ISOLanguageCode>] [-listiso]
                 [-showChoicesXML] [-applyChoiceChangesXML <pathToFile>]
                 [-showChoicesAfterApplyingChangesXML <pathtoFile>]
                 -pkg <pathToPackage>
                 -target <[DomainKey|MountPoint]>
hdiutil: detach failed - No such file or directory
Installation failed
Version:

Please file a Bug Report at https://github.com/chef/omnitruck/issues/new
Alternatively, feel free to open a Support Ticket at https://www.chef.io/support/tickets
More Chef support resources can be found at https://www.chef.io/support
<img width="399" alt="screen shot 2018-06-29 at 12 49 12 pm" src="https://user-images.githubusercontent.com/35344886/42078990-0e26098e-7b9c-11e8-87c7-4df3bc10034a.png">

Please include as many details about the problem as possible i.e., how to reproduce
the problem (if possible), type of the Operating System and its version, etc.,
and any other relevant details that might help us with troubleshooting.

**Comment by jtimberman** [comment]
Hello,

I'm sorry that we never followed up on this issue. I'm unable to reproduce this problem on my Mac, running 10.14. As the problem seems to be at the OS level, it's out of omnitruck's purview. If this is still a problem please open a new issue with complete details including macOS version, hardware information, etc.

Cheers
Joshua
