### ISSUE TITLE
Error bootstrapping a node using curl -L https://omnitruck.chef.io/install.sh

### ISSUE THREAD

**Issue by bizsuggestworks** [chef/omnitruck#376]
Here is the error:

oracle linux server 7.4 x86_64
Getting information for chef stable  for oracle linux server...
downloading https://omnitruck.chef.io/stable/chef/metadata?v=&p=oracle linux server&pv=7.4&m=x86_64
  to file /tmp/install.sh.79973/metadata.txt
trying wget...
trying curl...
cat: /tmp/install.sh.79973/metadata.txt: No such file or directory

grep: /tmp/install.sh.79973/metadata.txt: No such file or directory
downloaded metadata file is corrupted or an uncaught error was encountered in downloading the file...
Version: 

Please file a Bug Report at https://github.com/chef/omnitruck/issues/new
Alternatively, feel free to open a Support Ticket at https://www.chef.io/support/tickets
More Chef support resources can be found at https://www.chef.io/support

Please include as many details about the problem as possible i.e., how to reproduce
the problem (if possible), type of the Operating System and its version, etc.,
and any other relevant details that might help us with troubleshooting.

**Comment by tas50** [comment]
@bizsuggestworks I'm having a hard time reproducing this. I just spun up a Oracle Linux 7.4 host in EC2 and ran the install.sh script without issues.

```
el 7 x86_64
Getting information for chef stable  for el...
downloading https://omnitruck-direct.chef.io/stable/chef/metadata?v=&p=el&pv=7&m=x86_64
  to file /tmp/install.sh.1770/metadata.txt
trying wget...
sha1	3997daaa81c2ff78cc490973d50181e5f9a08d77
sha256	711ed28d1bdfd385d83349d64e480bf76550ad8a69e0f72dc99209e1fae63321
url	https://packages.chef.io/files/stable/chef/14.5.33/el/7/chef-14.5.33-1.el7.x86_64.rpm
version	14.5.33
downloaded metadata file looks valid...
downloading https://packages.chef.io/files/stable/chef/14.5.33/el/7/chef-14.5.33-1.el7.x86_64.rpm
  to file /tmp/install.sh.1770/chef-14.5.33-1.el7.x86_64.rpm
trying wget...
Comparing checksum with sha256sum...

WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING

You are installing an omnibus package without a version pin.  If you are installing
on production servers via an automated process this is DANGEROUS and you will
be upgraded without warning on new releases, even to new major releases.
Letting the version float is only appropriate in desktop, test, development or
CI/CD environments.

WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING

Installing chef
installing with rpm...
warning: /tmp/install.sh.1770/chef-14.5.33-1.el7.x86_64.rpm: Header V4 DSA/SHA1 Signature, key ID 83ef826a: NOKEY
Preparing...                          ################################# [100%]
Updating / installing...
   1:chef-14.5.33-1.el7               ################################# [100%]
Thank you for installing Chef!
```


Are there any more details you can provide about the configuration of the system. It should just get identified as an RHEL 7.4 host.
