### ISSUE TITLE
Not able to bootstrap a ubuntu server

### ISSUE THREAD

**Issue by mohanakishore** [chef/omnitruck#397]
Not able to bootstrap a ubuntu server

I am trying to bootstrap a ubuntu server and I am getting error saying that " dpkg: error: dpkg frontend is locked by another process ".

## Software Version
Chef - 13.12.14
OS: ubuntu

Please find the error message below.

10.254.141.30 -----> Installing Chef Omnibus (-v 13)
10.254.141.30 downloading https://omnitruck-direct.chef.io/chef/install.sh
10.254.141.30   to file /tmp/install.sh.15900/install.sh
10.254.141.30 trying wget...
10.254.141.30 ubuntu 18.04 x86_64
10.254.141.30 Getting information for chef stable 13 for ubuntu...
10.254.141.30 downloading https://omnitruck-direct.chef.io/stable/chef/metadata?v=13&p=ubuntu&pv=18.04&m=x86_64
10.254.141.30   to file /tmp/install.sh.15941/metadata.txt
10.254.141.30 trying wget...
10.254.141.30 sha1      d4245bff62f19cd84d4500f3abb23d5e0ee557c1
10.254.141.30 sha256    a2373e135bc22768f186f099b5ac824ce38e57969d92a1d1c23bfec50094199c
10.254.141.30 url       https://packages.chef.io/files/stable/chef/13.12.14/ubuntu/18.04/chef_13.12.14-1_amd64.deb
10.254.141.30 version   13.12.14
10.254.141.30 downloaded metadata file looks valid...
10.254.141.30 downloading https://packages.chef.io/files/stable/chef/13.12.14/ubuntu/18.04/chef_13.12.14-1_amd64.deb
10.254.141.30   to file /tmp/install.sh.15941/chef_13.12.14-1_amd64.deb
10.254.141.30 trying wget...
10.254.141.30 Comparing checksum with sha256sum...
10.254.141.30 Installing chef 13
10.254.141.30 installing with dpkg...
10.254.141.30 dpkg: error: dpkg frontend is locked by another process
10.254.141.30 Installation failed
10.254.141.30 Version: 13
10.254.141.30
10.254.141.30 Please file a Bug Report at https://github.com/chef/omnitruck/issues/new
10.254.141.30 Alternatively, feel free to open a Support Ticket at https://www.chef.io/support/tickets
10.254.141.30 More Chef support resources can be found at https://www.chef.io/support
10.254.141.30
10.254.141.30 Please include as many details about the problem as possible i.e., how to reproduce
10.254.141.30 the problem (if possible), type of the Operating System and its version, etc.,
10.254.141.30 and any other relevant details that might help us with troubleshooting.
10.254.141.30
10.254.141.30 Starting the first Chef Client run...
10.254.141.30 sh: 230: chef-client: not found

**Comment by tas50** [comment]
This means that another package is currently being installed on your system. Any package install locks dpkg and doesn't allow any other package installs. You probably have auto updates installing and Chef can't work around that. You just have to try again when another package isn't locked dpkg.
