### ISSUE TITLE
knife boostrap can't create transaction lock on /var/lib/rpm/.rpm.lock (Permission denied)

### ISSUE THREAD

**Issue by rridpath** [chef/omnitruck#411]
# Describe the problem
Running knife boostrap from chef workstation is giving permission denied error when installing rpm on client.

## Software Version
chef-workstation.x86_64                     0.4.1-1.el6
CentOS Linux release 7.6.1810 (Core)

## Replication Case
This is the command I ran:
knife bootstrap myserver.ec2.internal -U myUser -P myPw -i ~/.ssh/id_rsa -N RR-chef-test-client  --use-sudo-password

I was following this website to get things setup:
https://www.itzgeek.com/how-tos/linux/centos-how-tos/setup-chef-12-centos-7-rhel-7.html/3

## Stacktrace

Node RR-chef-test-client exists, overwrite it? (Y/N) y
Client RR-chef-test-client exists, overwrite it? (Y/N) y
Creating new client for RR-chef-test-client
Creating new node for RR-chef-test-client
Connecting to ip-10-0-17-156.ec2.internal
WARN: [SSH] PTY requested: stderr will be merged into stdout
The authenticity of host 'ip-10-0-17-156.ec2.internal (10.0.17.156)' can't be established.
fingerprint is SHA256:yEsorwcg20CL/3LAxhQWQnAT+hKjsoxohZt3ruJplbI.

Are you sure you want to continue connecting
? (Y/N) y
WARN: [SSH] PTY requested: stderr will be merged into stdout
Bootstrapping ip-10-0-17-156.ec2.internal
 [ip-10-0-17-156.ec2.internal] -----> Installing Chef Omnibus (stable/15)
downloading https://omnitruck.chef.io/chef/install.sh
  to file /tmp/install.sh.14517/install.sh
trying wget...
 [ip-10-0-17-156.ec2.internal] el 7 x86_64
Getting information for chef stable 15 for el...
downloading https://omnitruck.chef.io/stable/chef/metadata?v=15&p=el&pv=7&m=x86_64
  to file /tmp/install.sh.14522/metadata.txt
 [ip-10-0-17-156.ec2.internal] trying wget...
 [ip-10-0-17-156.ec2.internal] sha1	bcb835748819813842b664d7bdb1cf509eb71c09
sha256	85365d0a4c68a3445743d18e70055d762648bf673fc95f1e0e17194701f64d5f
url	https://packages.chef.io/files/stable/chef/15.0.300/el/7/chef-15.0.300-1.el7.x86_64.rpm
version	15.0.300
 [ip-10-0-17-156.ec2.internal] downloaded metadata file looks valid...
 [ip-10-0-17-156.ec2.internal] downloading https://packages.chef.io/files/stable/chef/15.0.300/el/7/chef-15.0.300-1.el7.x86_64.rpm
  to file /tmp/install.sh.14522/chef-15.0.300-1.el7.x86_64.rpm
 [ip-10-0-17-156.ec2.internal] trying wget...
 [ip-10-0-17-156.ec2.internal] Comparing checksum with sha256sum...
 [ip-10-0-17-156.ec2.internal] Installing chef 15
installing with rpm...
 [ip-10-0-17-156.ec2.internal] warning: /tmp/install.sh.14522/chef-15.0.300-1.el7.x86_64.rpm: Header V4 DSA/SHA1 Signature, key ID 83ef826a: NOKEY
 [ip-10-0-17-156.ec2.internal] error: can't create transaction lock on /var/lib/rpm/.rpm.lock (Permission denied)
Installation failed
Version: 15

Please file a Bug Report at https://github.com/chef/omnitruck/issues/new
Alternatively, feel free to open a Support Ticket at https://www.chef.io/support/tickets
More Chef support resources can be found at https://www.chef.io/support

Please include as many details about the problem as possible i.e., how to reproduce
the problem (if possible), type of the Operating System and its version, etc.,
and any other relevant details that might help us with troubleshooting.

 [ip-10-0-17-156.ec2.internal] mkdir: cannot create directory ‘/etc/chef’: Permission denied
 [ip-10-0-17-156.ec2.internal] sh: line 181: /etc/chef/client.pem: No such file or directory
 [ip-10-0-17-156.ec2.internal] chmod: cannot access ‘/etc/chef/client.pem’: No such file or directory
 [ip-10-0-17-156.ec2.internal] mkdir: cannot create directory ‘/etc/chef’: Permission denied
 [ip-10-0-17-156.ec2.internal] sh: line 216: /etc/chef/trusted_certs/ip-10-0-52-152_ec2_internal.crt: No such file or directory
 [ip-10-0-17-156.ec2.internal] sh: line 247: /etc/chef/client.rb: No such file or directory
 [ip-10-0-17-156.ec2.internal] sh: line 257: /etc/chef/first-boot.json: No such file or directory
Starting the first Chef Infra Client Client run...
sh: line 264: chef-client: command not found
ERROR: The following error occurred on ip-10-0-17-156.ec2.internal:
ERROR:

**Comment by RealElias** [comment]
Faced this weird stuff. Added 'sudo' to bootstrap template file: ` sh -c '` ->  `sudo sh -c '`
/opt/chefdk/embedded/lib/ruby/gems/2.6.0/gems/chef-15.2.20/lib/chef/knife/bootstrap/templates/chef-full.erb
It works now like a charm

**Comment by yeon432** [comment]
> Faced this weird stuff. Added 'sudo' to bootstrap template file: ` sh -c '` -> `sudo sh -c '` /opt/chefdk/embedded/lib/ruby/gems/2.6.0/gems/chef-15.2.20/lib/chef/knife/bootstrap/templates/chef-full.erb It works now like a charm

can you please little evaporate the coommand,still im facing same issue
