### ISSUE TITLE
Metadata endpoint intermittently returning empty body

### ISSUE THREAD

**Issue by bjwyse** [chef/omnitruck#414]
Intermittent calls to the metadata endpoint are returning an empty body with HTTP status code 200. It is causing failures in the PowerShell installation script.

# Describe the problem
PowerShell installation fails with error:

```
There was an error: 
	Exception calling "DownloadFile" with "2" argument(s): "Value cannot be null.
```

## Software Version
Using Chef installation PowerShell script from AWS OpsWorks starter kit.

## Replication Case
Run the Chef installation PowerShell script on Windows Server 2012 R2 or Windows Server 2016.

## Stacktrace
```
PS C:\Windows\system32> C:\Program Files\Amazon\Ec2ConfigService\Scripts\UserScript.ps1
Installing AWS CLI...
Successfully downloaded the AWS CLI Installation
Installing Chef-Client...
VERBOSE: Platform: windows
VERBOSE: Platform Version: 2012r2
VERBOSE: Architecture: x86_64
VERBOSE: Project: chef
VERBOSE: Downloading chef details from https://omnitruck.chef.io/stable/chef/metadata?v=13.8.5&p=windows&pv=2012r2&m=x86_64
VERBOSE: Project details: 
VERBOSE: 	 = 
VERBOSE: Download directory: C:\Users\admin\AppData\Local\Temp
VERBOSE: Filename: 
VERBOSE: Found existing installer at C:\Users\admin\AppData\Local\Temp\.
VERBOSE: Checksum not specified, existing installer ignored.
VERBOSE: Performing the operation "Download chef" on target "".
VERBOSE: Downloading chef from  to C:\Users\admin\AppData\Local\Temp\.
There was an error: 
	Exception calling "DownloadFile" with "2" argument(s): "Value cannot be null.
Parameter name: address"
	Value cannot be null.
Parameter name: address
Failed to download from .
At line:70 char:5
+     throw "Failed to download from $uri."
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Failed to download from .:String) [], RuntimeException
    + FullyQualifiedErrorId : Failed to download from .
 

PS C:\Windows\system32> 
```
</details>

## Possible Solution
No possible solution. As mentioned, the problem is intermittent.

**Comment by bjwyse** [comment]
![empty-metadata](https://user-images.githubusercontent.com/511510/63029940-5a955f80-bea9-11e9-9706-cfb5db268ad7.png)

**Comment by dhaneshcode** [comment]
Have the same issue when trying to install the chef info ubuntu and awslinux. The api request gives out empty metadata file into tmp directory.

**Comment by lukeseawalker** [comment]
We are experiencing the same issue, metadata file returned with 0 length.

**Comment by matteofiordarancio** [comment]
We have the same problem too

**Comment by bjwyse** [comment]
I am able to workaround by providing the download URL directly using `download_url_override`.
Obviously only works if you know the URL for the installer you need.

```
# Chef client installation.
# https://docs.chef.io/install_omnibus.html
function install_chef_client {
  Write-Host "Installing Chef-Client..."
  . { Invoke-WebRequest -UseBasicParsing https://omnitruck.chef.io/install.ps1 } | Invoke-Expression; install -version "$env:CHEF_CLIENT_VERSION" -download_url_override "https://packages.chef.io/files/stable/chef/13.8.5/windows/2016/chef-client-13.8.5-1-x64.msi" -Verbose 
  # Update Path environment variable to include new Chef folder
  $env:Path = [System.Environment]::GetEnvironmentVariable("Path","Machine") + ";" + [System.Environment]::GetEnvironmentVariable("Path","User")
}
```

**Comment by blamarvt** [comment]
I am unable to install using `omnitruck`:

```
$ curl -i 'https://omnitruck.chef.io/install.sh'
HTTP/2 200 
server: WEBrick/1.3.1 (Ruby/2.4.5/2018-10-18)
accept-ranges: bytes
date: Wed, 14 Aug 2019 16:37:15 GMT
via: 1.1 varnish
age: 2034
x-served-by: cache-dca17777-DCA
x-cache: HIT
x-cache-hits: 4
x-timer: S1565800635.106287,VS0,VE7
content-length: 0
```

I can only get the install file if I set an `Accept` header:

```
b@bx1c:~$ curl -i 'https://omnitruck.chef.io/install.sh' -H 'accept: text/html'
HTTP/2 200 
content-type: application/x-sh
server: WEBrick/1.3.1 (Ruby/2.4.5/2018-10-18)
x-content-type-options: nosniff
accept-ranges: bytes
date: Wed, 14 Aug 2019 16:38:26 GMT
via: 1.1 varnish
age: 419
x-served-by: cache-dca17752-DCA
x-cache: HIT
x-cache-hits: 1
x-timer: S1565800707.945495,VS0,VE3
content-length: 23103

#!/bin/sh
# WARNING: REQUIRES /bin/sh
<snip>
```

**Comment by bytebeast** [comment]
Ran a test and found that the only cache that is serving properly is from SEA **cache-sea####-SEA**. The other 2 caches are serving no data, **cache-pao####-PAO** and **cache-sjc####-SJC**

**Comment by bytebeast** [comment]
The only cache that is working is SEA, the other 2 caches (POA & SJC) are returning empty bodie.

**Comment by bytebeast** [comment]
Just incase anyone did not know the status on this...it was resolvd yesterday.
![Chef_Status](https://user-images.githubusercontent.com/19381562/63109506-3df73700-bf3e-11e9-9d35-e69a2dc9c5be.png)

**Comment by brandonhawbaker** [comment]
No, it's not resolved.  I experienced this issue today.

"Exception calling "DownloadFile" with "2" argument(s): "Value cannot be null.
Parameter name: address"
	Value cannot be null."

**Comment by antage** [comment]
The same problem:

```
Unable to retrieve a valid package!
Version: 15

...

Metadata URL: https://omnitruck.chef.io/stable/chef/metadata?v=15&p=debian&pv=10&m=x86_64

DEBUG OUTPUT FOLLOWS:

STDERR from curl:

HTTP/2 200 
server: WEBrick/1.3.1 (Ruby/2.4.5/2018-10-18)
accept-ranges: bytes
date: Sat, 30 Nov 2019 09:09:41 GMT
via: 1.1 varnish
age: 0
x-served-by: cache-hhn4052-HHN
x-cache: MISS
x-cache-hits: 0
x-timer: S1575104980.367050,VS0,VE805
content-length: 0
```

**Comment by brandonhawbaker** [comment]
In my case, I kept seeing the issue until I closed my powershell window and re-opened another chefdk command prompt.

**Comment by lamont-granquist** [comment]
Closing this as the incident is over.

GH tickets against the code is also not the right way to report incidents, you're better off hopping onto the slack channel.

**Comment by brandonhawbaker** [comment]
What's a GH incident @lamont-granquist ?  Are you saying this was a server side issue having nothing to do Chef?  If so then this is still a relevant issue in the sense that the connection should be checked and there should be retry attempts that can be defined and if it can't succeed in connecting then the error message should suggest what's wrong.
