### ISSUE TITLE
Downloading chef failed https://www.chef.io/chef/install.sh

### ISSUE THREAD

**Issue by pankaj8727** [chef/omnitruck#416]
sudo curl -L https://www.chef.io/chef/install.sh | sudo bash -s -- -v 12.3.0
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 23097  100 23097    0     0  1037k      0 --:--:-- --:--:-- --:--:-- 1074k
ubuntu 14.04 x86_64
Getting information for chef stable 12.3.0 for ubuntu...
downloading https://www.chef.io/stable/chef/metadata?v=12.3.0&p=ubuntu&pv=14.04&m=x86_64
  to file /tmp/install.sh.19467/metadata.txt
trying wget...
trying curl...
trying perl...
trying python...
Unable to retrieve a valid package!
Version: 12.3.0

Please file a Bug Report at https://github.com/chef/omnitruck/issues/new
Alternatively, feel free to open a Support Ticket at https://www.chef.io/support/tickets
More Chef support resources can be found at https://www.chef.io/support

Please include as many details about the problem as possible i.e., how to reproduce
the problem (if possible), type of the Operating System and its version, etc.,
and any other relevant details that might help us with troubleshooting.

Metadata URL: https://www.chef.io/stable/chef/metadata?v=12.3.0&p=ubuntu&pv=14.04&m=x86_64
\nDEBUG OUTPUT FOLLOWS:\n\nSTDERR from wget:\n\n--2019-10-11 11:16:10--  https://www.chef.io/stable/chef/metadata?v=12.3.0&p=ubuntu&pv=14.04&m=x86_64
Resolving www.chef.io (www.chef.io)... 151.101.250.110
Connecting to www.chef.io (www.chef.io)|151.101.250.110|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 0
Saving to: ‘/tmp/install.sh.19467/metadata.txt’

     0K                                                        0.00 =0s

2019-10-11 11:16:11 (0.00 B/s) - ‘/tmp/install.sh.19467/metadata.txt’ saved [0/0]\n\nSTDERR from curl:\n\nHTTP/1.1 200 OK 
Server: WEBrick/1.3.1 (Ruby/2.4.5/2018-10-18)
Content-Length: 0
Accept-Ranges: bytes
Date: Fri, 11 Oct 2019 11:16:11 GMT
Via: 1.1 varnish
Age: 0
Connection: keep-alive
X-Served-By: cache-bwi5034-BWI
X-Cache: HIT
X-Cache-Hits: 1
X-Timer: S1570792571.388544,VS0,VE1
Strict-Transport-Security: max-age= 7776000; includeSubDomains
X-Frame-Options: SAMEORIGIN
\n\nSTDERR from perl:\n\nCan't locate LWP/Simple.pm in @INC (you may need to install the LWP::Simple module) (@INC contains: /etc/perl /usr/local/lib/perl/5.18.2 /usr/local/share/perl/5.18.2 /usr/lib/perl5 /usr/share/perl5 /usr/lib/perl/5.18 /usr/share/perl/5.18 /usr/local/lib/site_perl .) at -e line 1.
BEGIN failed--compilation aborted at -e line 1.\n\nSTDERR from python:\n\n\n

**Comment by lamont-granquist** [comment]
seems to be another dup of #414
