### ISSUE TITLE
should prefer a new 'url' key over 'relpath' in the metadata

### ISSUE THREAD

**Issue by lamont-granquist** [chef/omnitruck#47]
having metadata entries like this:

``` ruby
  "el": {
    "6": {
      "x86_64": {
        "0.2.2-1": {
          "relpath": "/el/6/x86_64/chefdk-0.2.2-1.x86_64.rpm",
          "md5": "5da3f329f7e6d51e778212dea4dae73f",
          "sha256": "2bc4c5c6f82ee7abed385d837e526fd40777ddc47ad939e4f3ecea625b43a245"
        }
      }
    }
  },
```

hardcodes the path relative to the s3 bucket.   we can extend the api to also support urls:

``` ruby
  "debian": {
    "6": {
      "x86_64": {
        "0.2.2-1": {
          "url": "https://packagecloud.io/chef/stable/download?distro=squeeze&filename=chefdk_0.2.2-1_amd64.deb",
          "md5": "fbb5a0168618fc0eb5f0184b2cc466b1",
          "sha256": "7b66a28ead4c2a0a1b3317f75f653d109527b0e5a4ae569475b715d38cf986f3"
        }
      }
    }
  },
```

then we can point the downloads at arbitrary things.  if url is present, omnitruck would just serve the url, if the relpath is present it would be backwards compatible.  then we could lazily start publishing new stuff to packagecloud.io and start pointing omnitruck at it, and could move old stuff over to packagecloud.io in pieces.

**Comment by jtimberman** [comment]
I'm closing this because the work hasn't been prioritized by anyone since the issue was opened. We may revisit design and functionality in Omnitruck at some point, and will consider this for future development. As such, the futuredev label has been added.
