### ISSUE TITLE
Error vagrant provisioning

### ISSUE THREAD

**Issue by jonardcaguioa** [chef/omnitruck#511]
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

sh /tmp/vagrant-omnibus/install.sh -v 16.4.38 2>&1

Stdout from the command:

ubuntu 18.04 x86_64
Getting information for chef stable 16.4.38 for ubuntu...
downloading https://omnitruck.chef.io/stable/chef/metadata?v=16.4.38&p=ubuntu&pv=18.04&m=x86_64
  to file /tmp/install.sh.3338/metadata.txt
trying wget...
sha1    924a4c083ce84f997bb1cd9fa3563859b4330d14
sha256  39db6b5fdc9f552f3f8011cb07ae11e3c61c95d00366cb5fd4b83ed4e3267be2
url     https://packages.chef.io/files/stable/chef/16.4.38/ubuntu/18.04/chef_16.4.38-1_amd64.deb
version 16.4.38
downloaded metadata file looks valid...
downloading https://packages.chef.io/files/stable/chef/16.4.38/ubuntu/18.04/chef_16.4.38-1_amd64.deb
  to file /tmp/install.sh.3338/chef_16.4.38-1_amd64.deb
trying wget...
trying curl...
Comparing checksum with sha256sum...
Installing chef 16.4.38
installing with dpkg...
dpkg-deb: error: '/tmp/install.sh.3338/chef_16.4.38-1_amd64.deb' is not a Debian format archive
dpkg: error processing archive /tmp/install.sh.3338/chef_16.4.38-1_amd64.deb (--install):
 dpkg-deb --control subprocess returned error exit status 2
Errors were encountered while processing:
 /tmp/install.sh.3338/chef_16.4.38-1_amd64.deb
Installation failed
Version: 16.4.38

Please file a Bug Report at https://github.com/chef/omnitruck/issues/new
Alternatively, feel free to open a Support Ticket at https://www.chef.io/support/tickets
More Chef support resources can be found at https://www.chef.io/support

Please include as many details about the problem as possible i.e., how to reproduce
the problem (if possible), type of the Operating System and its version, etc.,
and any other relevant details that might help us with troubleshooting.

Stderr from the command:

**Comment by anandhapadmanabhan** [comment]
@jonardcaguioa There was a glitch with our artifactory, which might have caused this issue. Can you retry it once and see if the issue still persists?
